# **Group Hackaholics**

# Python Libraries

In [ ]:
#analysis the data and wrangling
import pandas as pd
import numpy as np
import random as rnd

# Importing E-Commerce dataset with csv format

In [ ]:
session_df = pd.read_csv('session.csv')
session_df.head()

   session_id  customer_id           start_time   device   source country
0           1        12360  2021-12-27T00:01:36   mobile    email      DE
1           2        13917  2025-01-31T21:29:42  desktop  organic      PL
2           3         1022  2024-02-19T00:52:50   tablet  organic      FR
3           4         2882  2024-08-04T19:54:31   mobile   direct      GB
4           5         1286  2022-06-28T13:58:08  desktop    email      ES

In [ ]:
customers_df = pd.read_csv('customers.csv')

print(customers_df.head())

   customer_id              name                       email country  age  \
0            1  Jennifer Salinas      nicholas59@example.org      JP   71
1            2     Phillip Ramos  christinarubio@example.com      IN   26
2            3       Dawn Fowler       jessica03@example.org      BR   21
3            4      Mario Butler         paula27@example.org      FR   63
4            5       Amber Brown         kevin85@example.net      BR   19

  signup_date  marketing_opt_in
0  2020-09-04              True
1  2020-04-05             False
2  2023-08-31              True
3  2022-06-30              True
4  2022-07-22              True

In [ ]:
events_df = pd.read_csv('events.csv')

print(events_df.head())

   event_id  session_id            timestamp   event_type  product_id  qty  \
0         1           1  2021-12-27T00:08:36    page_view        93.0  NaN
1         2           1  2021-12-27T00:16:36    page_view      1005.0  NaN
2         3           1  2021-12-27T00:18:01  add_to_cart      1005.0  1.0
3         4           1  2021-12-27T00:45:36    page_view       918.0  NaN
4         5           1  2021-12-27T01:03:36    page_view       946.0  NaN

   cart_size payment  discount_pct  amount_usd
0        NaN     NaN           NaN         NaN
1        NaN     NaN           NaN         NaN
2        NaN     NaN           NaN         NaN
3        NaN     NaN           NaN         NaN
4        NaN     NaN           NaN         NaN

In [ ]:
orderItems_df = pd.read_csv('order_items.csv')

print(orderItems_df.head())

   order_id  product_id  unit_price_usd  quantity  line_total_usd
0         1         226          107.15         1          107.15
1         2         771          116.17         1          116.17
2         3         415           94.49         1           94.49
3         3          24           42.86         1           42.86
4         4        1157           32.18         1           32.18

In [ ]:
orders_df = pd.read_csv('orders.csv')

print(orders_df.head())

   order_id  customer_id           order_time payment_method  discount_pct  \
0         1        13917  2025-01-31T23:07:42           card            20
1         2         1022  2024-02-19T01:17:50           card             0
2         3         6145  2024-12-04T20:24:13           card             0
3         4         3152  2024-07-17T08:50:47           card            15
4         5        12378  2020-08-21T16:54:16           card             0

   subtotal_usd  total_usd country   device   source
0        107.15      85.72      PL  desktop  organic
1        116.17     116.17      FR   tablet  organic
2        137.35     137.35      US   mobile  organic
3         32.18      27.35      BR   mobile    email
4        238.09     238.09      NL  desktop     paid

In [ ]:
products_df = pd.read_csv('products.csv')

print(products_df.head())

   product_id     category                      name  price_usd  cost_usd  \
0           1  Electronics        SSD MediumBlue 149     570.28    352.69
1           2  Electronics     Keyboard DeepPink 696     498.13    263.13
2           3  Electronics     Headphones Orchid 188     548.53    309.60
3           4  Electronics  Smartwatch BurlyWood 664     268.36    153.56
4           5  Electronics   Smartwatch Cornsilk 328      63.69     42.65

   margin_usd
0      217.59
1      235.00
2      238.93
3      114.80
4       21.04

In [ ]:
reviews_df = pd.read_csv('reviews.csv')

print(reviews_df.head())

   review_id  order_id  product_id  rating  \
0          1         4        1157       2
1          2         7         405       4
2          3         7         487       5
3          4         7         442       5
4          5         7         348       4

                            review_text          review_time
0                    Not great quality.  2022-02-01T00:00:00
1                 Good value for money!  2020-03-07T00:00:00
2  Excellent product, highly recommend!  2024-12-26T00:00:00
3  Excellent product, highly recommend!  2021-03-18T00:00:00
4                 Good value for money!  2025-09-30T00:00:00

# Analyze, Cleaning and Transform Datasets

# Analyse session_df Dataset

In [ ]:
session_df.head(10)

   session_id  customer_id           start_time   device   source country
0           1        12360  2021-12-27T00:01:36   mobile    email      DE
1           2        13917  2025-01-31T21:29:42  desktop  organic      PL
2           3         1022  2024-02-19T00:52:50   tablet  organic      FR
3           4         2882  2024-08-04T19:54:31   mobile   direct      GB
4           5         1286  2022-06-28T13:58:08  desktop    email      ES
5           6         2319  2020-07-22T20:10:01   mobile     paid      SG
6           7         7050  2023-05-07T14:35:49   mobile    email      GB
7           8         5687  2020-07-10T10:35:54   mobile    email      DE
8           9         6476  2024-02-22T16:57:44   mobile   direct      PL
9          10         6145  2024-12-04T18:53:13   mobile  organic      US

In [ ]:
session_df.shape

(120000, 6)

In [ ]:
session_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 6 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   session_id   120000 non-null  int64
 1   customer_id  120000 non-null  int64
 2   start_time   120000 non-null  object
 3   device       120000 non-null  object
 4   source       120000 non-null  object
 5   country      120000 non-null  object
dtypes: int64(2), object(4)
memory usage: 5.5+ MB

In [ ]:
print (session_df.columns.values)

['session_id' 'customer_id' 'start_time' 'device' 'source' 'country']

In [ ]:
#showing the datatypes of the column
session_df.dtypes

session_id      int64
customer_id     int64
start_time     object
device         object
source         object
country        object
dtype: object

In [ ]:
print(session_df.count())

session_id     120000
customer_id    120000
start_time     120000
device         120000
source         120000
country        120000
dtype: int64

In [ ]:
#describe the dataframe with showing the count, mean, standard deviation, min, percentiles, and max.
session_df.describe()

          session_id    customer_id
count  120000.000000  120000.000000
mean    60000.500000   10020.814533
std     34641.160489    5790.838535
min         1.000000       1.000000
25%     30000.750000    5003.000000
50%     60000.500000   10023.000000
75%     90000.250000   15052.000000
max    120000.000000   20000.000000

Check Null value

In [ ]:
#shows the number of null values in the dataframe
print("Number of NaN values for each columns: ")
session_df.isna().sum()

Number of NaN values for each columns:

session_id     0
customer_id    0
start_time     0
device         0
source         0
country        0
dtype: int64

In [ ]:
#check duplicate
session_df.duplicated().sum()

np.int64(0)

In [ ]:
session_df.head()

   session_id  customer_id           start_time   device   source country
0           1        12360  2021-12-27T00:01:36   mobile    email      DE
1           2        13917  2025-01-31T21:29:42  desktop  organic      PL
2           3         1022  2024-02-19T00:52:50   tablet  organic      FR
3           4         2882  2024-08-04T19:54:31   mobile   direct      GB
4           5         1286  2022-06-28T13:58:08  desktop    email      ES

In [ ]:
session_df['start_time'] = pd.to_datetime(session_df['start_time'])

In [ ]:
session_df['session_date'] = session_df['start_time'].dt.date

In [ ]:
session_df['session_time'] = session_df['start_time'].dt.time

In [ ]:
session_df[['start_time', 'session_date', 'session_time']].head()

           start_time session_date session_time
0 2021-12-27 00:01:36   2021-12-27     00:01:36
1 2025-01-31 21:29:42   2025-01-31     21:29:42
2 2024-02-19 00:52:50   2024-02-19     00:52:50
3 2024-08-04 19:54:31   2024-08-04     19:54:31
4 2022-06-28 13:58:08   2022-06-28     13:58:08

In [ ]:
session_df.head()

,session_id,customer_id,start_time,device,source,country,session_date,session_time
0,1,12360,2021-12-27 00:01:36,mobile,email,DE,2021-12-27,00:01:36
1,2,13917,2025-01-31 21:29:42,desktop,organic,PL,2025-01-31,21:29:42
2,3,1022,2024-02-19 00:52:50,tablet,organic,FR,2024-02-19,00:52:50
3,4,2882,2024-08-04 19:54:31,mobile,direct,GB,2024-08-04,19:54:31
4,5,1286,2022-06-28 13:58:08,desktop,email,ES,2022-06-28,13:58:08

In [ ]:
session_df=session_df.drop (columns=['start_time'])

In [ ]:
session_df.head()

   session_id  customer_id   device   source country session_date session_time
0           1        12360   mobile    email      DE   2021-12-27     00:01:36
1           2        13917  desktop  organic      PL   2025-01-31     21:29:42
2           3         1022   tablet  organic      FR   2024-02-19     00:52:50
3           4         2882   mobile   direct      GB   2024-08-04     19:54:31
4           5         1286  desktop    email      ES   2022-06-28     13:58:08

Change country shortform to full name

In [ ]:
#list of country in session_df
sorted(session_df['country'].unique())

['AE',
 'AU',
 'BR',
 'CA',
 'DE',
 'ES',
 'FR',
 'GB',
 'IN',
 'JP',
 'MX',
 'NL',
 'PL',
 'SE',
 'SG',
 'US',
 'ZA']

In [ ]:
country_map = {
    'AE': 'United Arab Emirates',
    'AU': 'Australia',
    'BR': 'Brazil',
    'CA': 'Canada',
    'DE': 'Germany',
    'ES': 'Spain',
    'FR': 'France',
    'GB': 'United Kingdom',
    'IN': 'India',
    'JP': 'Japan',
    'MX': 'Mexico',
    'NL': 'Netherlands',
    'PL': 'Poland',
    'SE': 'Sweden',
    'SG': 'Singapore',
    'US': 'United States',
    'ZA': 'South Africa'
}

session_df['country'] = session_df['country'].map(country_map)

In [ ]:
#list of updated country in session_df
sorted(session_df['country'].unique())

['Australia',
 'Brazil',
 'Canada',
 'France',
 'Germany',
 'India',
 'Japan',
 'Mexico',
 'Netherlands',
 'Poland',
 'Singapore',
 'South Africa',
 'Spain',
 'Sweden',
 'United Arab Emirates',
 'United Kingdom',
 'United States']

In [ ]:
session_df.head()

,session_id,customer_id,device,source,country,session_date,session_time
0,1,12360,mobile,email,Germany,2021-12-27,00:01:36
1,2,13917,desktop,organic,Poland,2025-01-31,21:29:42
2,3,1022,tablet,organic,France,2024-02-19,00:52:50
3,4,2882,mobile,direct,United Kingdom,2024-08-04,19:54:31
4,5,1286,desktop,email,Spain,2022-06-28,13:58:08

In [ ]:
#recheck datatype
session_df.dtypes

session_id       int64
customer_id      int64
device          object
source          object
country         object
session_date    object
session_time    object
dtype: object

In [ ]:
#recheck the number of null values in the dataframe
print("Number of NaN values for each columns: ")
session_df.isna().sum()

Number of NaN values for each columns:

session_id      0
customer_id     0
device          0
source          0
country         0
session_date    0
session_time    0
dtype: int64

In [ ]:
#recheck duplicate
session_df.duplicated().sum()

np.int64(0)

Validate categorical column in session_df

In [ ]:
session_df['session_id'].nunique()

120000

In [ ]:
session_df['device'].value_counts()

device
mobile     65942
desktop    45547
tablet      8511
Name: count, dtype: int64

In [ ]:
session_df['source'].value_counts()

source
organic     40776
direct      29861
paid        14465
social      14389
email       10949
referral     9560
Name: count, dtype: int64

In [ ]:
session_df['country'].value_counts()

country
United States           21913
India                    9567
United Kingdom           9451
Brazil                   8573
Germany                  8332
France                   7811
Mexico                   7286
Australia                6443
Canada                   6057
Japan                    5841
Spain                    5580
Netherlands              5261
Singapore                4780
Sweden                   3702
Poland                   3630
United Arab Emirates     3424
South Africa             2349
Name: count, dtype: int64

In [ ]:
#Check total number of country
session_df['country'].nunique()

17

# Analyse Customer Dataset

In [ ]:
customers_df.head(10)

,customer_id,name,email,country,age,signup_date,marketing_opt_in
0,1,Jennifer Salinas,nicholas59@example.org,JP,71,2020-09-04,True
1,2,Phillip Ramos,christinarubio@example.com,IN,26,2020-04-05,False
2,3,Dawn Fowler,jessica03@example.org,BR,21,2023-08-31,True
3,4,Mario Butler,paula27@example.org,FR,63,2022-06-30,True
4,5,Amber Brown,kevin85@example.net,BR,19,2022-07-22,True
5,6,Kevin Chapman,michaelpoole@example.org,US,28,2020-10-21,False
6,7,Timothy Sanchez,shannonbrown@example.org,IN,48,2025-07-24,False
7,8,Rachael Morales,tammy08@example.com,GB,33,2022-10-09,True
8,9,Laura Guzman,awright@example.org,US,32,2024-07-29,True
9,10,Alexander Lopez,brianmaxwell@example.org,JP,39,2023-01-13,True

In [ ]:
customers_df.shape

(20000, 7)

In [ ]:
customers_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       20000 non-null  int64
 1   name              20000 non-null  object
 2   email             20000 non-null  object
 3   country           20000 non-null  object
 4   age               20000 non-null  int64
 5   signup_date       20000 non-null  object
 6   marketing_opt_in  20000 non-null  bool
dtypes: bool(1), int64(2), object(4)
memory usage: 957.2+ KB

In [ ]:
print(customers_df.columns.values)

['customer_id' 'name' 'email' 'country' 'age' 'signup_date'
 'marketing_opt_in']

In [ ]:
print(customers_df.count())

customer_id         20000
name                20000
email               20000
country             20000
age                 20000
signup_date         20000
marketing_opt_in    20000
dtype: int64

In [ ]:
#describe the dataframe with showing the count, mean, standard deviation, min, percentiles, and max.
customers_df.describe()

        customer_id           age
count  20000.000000  20000.000000
mean   10000.500000     46.492550
std     5773.647028     16.767961
min        1.000000     18.000000
25%     5000.750000     32.000000
50%    10000.500000     46.500000
75%    15000.250000     61.000000
max    20000.000000     75.000000

Check Null Value

In [ ]:
#shows the number of null values in the dataframe
print("Number of NaN values for each columns: ")
customers_df.isna().sum()

Number of NaN values for each columns:

customer_id         0
name                0
email               0
country             0
age                 0
signup_date         0
marketing_opt_in    0
dtype: int64

In [ ]:
#Check duplicate
customers_df.duplicated().sum()

np.int64(0)

from null and duplicate check Customer dataframe not have null value and duplicate

Validate categorical column in customers_df

In [ ]:
customers_df['country'].value_counts()

country
US    3648
IN    1589
GB    1585
BR    1421
DE    1397
FR    1325
MX    1206
AU    1045
CA    1015
JP     974
ES     950
NL     874
SG     797
SE     621
PL     605
AE     560
ZA     388
Name: count, dtype: int64

In [ ]:
#change country name to its full name
#based on previous country_map
print(country_map)

{'AE': 'United Arab Emirates', 'AU': 'Australia', 'BR': 'Brazil', 'CA': 'Canada', 'DE': 'Germany', 'ES': 'Spain', 'FR': 'France', 'GB': 'United Kingdom', 'IN': 'India', 'JP': 'Japan', 'MX': 'Mexico', 'NL': 'Netherlands', 'PL': 'Poland', 'SE': 'Sweden', 'SG': 'Singapore', 'US': 'United States', 'ZA': 'South Africa'}

In [ ]:
#change country name to full name
customers_df['country'] = customers_df['country'].map(country_map)

In [ ]:
# updated country name in customers_df
customers_df['country'].value_counts()

country
United States           3648
India                   1589
United Kingdom          1585
Brazil                  1421
Germany                 1397
France                  1325
Mexico                  1206
Australia               1045
Canada                  1015
Japan                    974
Spain                    950
Netherlands              874
Singapore                797
Sweden                   621
Poland                   605
United Arab Emirates     560
South Africa             388
Name: count, dtype: int64

In [ ]:
customers_df.head()

,customer_id,name,email,country,age,signup_date,marketing_opt_in
0,1,Jennifer Salinas,nicholas59@example.org,Japan,71,2020-09-04,True
1,2,Phillip Ramos,christinarubio@example.com,India,26,2020-04-05,False
2,3,Dawn Fowler,jessica03@example.org,Brazil,21,2023-08-31,True
3,4,Mario Butler,paula27@example.org,France,63,2022-06-30,True
4,5,Amber Brown,kevin85@example.net,Brazil,19,2022-07-22,True

In Marketing option column ( marketing_opt_in ) I want to change from boolean true false to Subscribe / unsubscribe

it shows that the subscribe or not the marketing

In [ ]:
# Convert boolean values in 'marketing_opt_in' to more readable labels
# True  -> Subscribed (customer agreed to receive marketing)
# False -> Unsubscribed (customer did not opt in for marketing)
customers_df['marketing_opt_in'] = customers_df['marketing_opt_in'].map({
    True: 'Subscribed',
    False: 'Unsubscribed'
})

In [ ]:
customers_df.head()

,customer_id,name,email,country,age,signup_date,marketing_opt_in
0,1,Jennifer Salinas,nicholas59@example.org,Japan,71,2020-09-04,Subscribed
1,2,Phillip Ramos,christinarubio@example.com,India,26,2020-04-05,Unsubscribed
2,3,Dawn Fowler,jessica03@example.org,Brazil,21,2023-08-31,Subscribed
3,4,Mario Butler,paula27@example.org,France,63,2022-06-30,Subscribed
4,5,Amber Brown,kevin85@example.net,Brazil,19,2022-07-22,Subscribed

In [ ]:
customers_df['age'].value_counts().sort_index()

age
18    330
19    352
20    367
21    361
22    326
23    339
24    339
25    350
26    349
27    319
28    351
29    327
30    357
31    404
32    336
33    360
34    345
35    332
36    332
37    345
38    365
39    339
40    330
41    392
42    355
43    300
44    310
45    327
46    361
47    310
48    344
49    353
50    341
51    322
52    372
53    351
54    364
55    381
56    350
57    336
58    298
59    338
60    334
61    356
62    365
63    352
64    341
65    308
66    310
67    356
68    377
69    363
70    349
71    346
72    356
73    369
74    321
75    337
Name: count, dtype: int64

In [ ]:
customers_df['age'].nunique()

58

from output above age range are 18 -75 years old

In [ ]:
# Group customer age into meaningful categories for better analysis and segmentation
customers_df['age_group'] = pd.cut(
    customers_df['age'],
    bins=[0,18,25,35,50,100],
    labels=['Teen (0–18 Years Old)','Young Adult (19-25 Years Old)','Adult (26-35 Years Old)','Mid Age (36-50 Years Old)','Senior (51-100 Years Old)']
)

Customer ages are grouped into categories (Teen, Young Adult, Adult, Mid Age, Senior) for easier analysis and visualization.

Age ranges:

0–18 → Teen

19–25 → Young Adult

26–35 → Adult

36–50 → Mid Age

51–100 → Senior

In [ ]:
customers_df.head(10)

,customer_id,name,email,country,age,signup_date,marketing_opt_in,age_group
0,1,Jennifer Salinas,nicholas59@example.org,Japan,71,2020-09-04,Subscribed,Senior (51-100 Years Old)
1,2,Phillip Ramos,christinarubio@example.com,India,26,2020-04-05,Unsubscribed,Adult (26-35 Years Old)
2,3,Dawn Fowler,jessica03@example.org,Brazil,21,2023-08-31,Subscribed,Young Adult (19-25 Years Old)
3,4,Mario Butler,paula27@example.org,France,63,2022-06-30,Subscribed,Senior (51-100 Years Old)
4,5,Amber Brown,kevin85@example.net,Brazil,19,2022-07-22,Subscribed,Young Adult (19-25 Years Old)
5,6,Kevin Chapman,michaelpoole@example.org,United States,28,2020-10-21,Unsubscribed,Adult (26-35 Years Old)
6,7,Timothy Sanchez,shannonbrown@example.org,India,48,2025-07-24,Unsubscribed,Mid Age (36-50 Years Old)
7,8,Rachael Morales,tammy08@example.com,United Kingdom,33,2022-10-09,Subscribed,Adult (26-35 Years Old)
8,9,Laura Guzman,awright@example.org,United States,32,2024-07-29,Subscribed,Adult (26-35 Years Old)
9,10,Alexander Lopez,brianmaxwell@example.org,Japan,39,2023-01-13,Subscribed,Mid Age (36-50 Years Old)

In [ ]:
customers_df = customers_df[
    ['customer_id', 'name', 'email', 'country', 'age', 'age_group',
     'signup_date', 'marketing_opt_in']
]

In [ ]:
print(customers_df.columns.values)

['customer_id' 'name' 'email' 'country' 'age' 'age_group' 'signup_date'
 'marketing_opt_in']

# Analyse Event Dataset

In [ ]:
events_df.head(10)

,event_id,session_id,timestamp,event_type,product_id,qty,cart_size,payment,discount_pct,amount_usd
0,1,1,2021-12-27T00:08:36,page_view,93.0,NaN,NaN,NaN,NaN,NaN
1,2,1,2021-12-27T00:16:36,page_view,1005.0,NaN,NaN,NaN,NaN,NaN
2,3,1,2021-12-27T00:18:01,add_to_cart,1005.0,1.0,NaN,NaN,NaN,NaN
3,4,1,2021-12-27T00:45:36,page_view,918.0,NaN,NaN,NaN,NaN,NaN
4,5,1,2021-12-27T01:03:36,page_view,946.0,NaN,NaN,NaN,NaN,NaN
5,6,1,2021-12-27T01:05:05,add_to_cart,946.0,1.0,NaN,NaN,NaN,NaN
6,7,1,2021-12-27T01:18:36,page_view,915.0,NaN,NaN,NaN,NaN,NaN
7,8,1,2021-12-27T01:37:36,page_view,931.0,NaN,NaN,NaN,NaN,NaN
8,9,1,2021-12-27T01:39:00,add_to_cart,931.0,1.0,NaN,NaN,NaN,NaN
9,10,1,2021-12-27T01:59:36,page_view,978.0,NaN,NaN,NaN,NaN,NaN

In [ ]:
events_df.shape

(760958, 10)

In [ ]:
events_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 760958 entries, 0 to 760957
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   event_id      760958 non-null  int64
 1   session_id    760958 non-null  int64
 2   timestamp     760958 non-null  object
 3   event_type    760958 non-null  object
 4   product_id    682469 non-null  float64
 5   qty           143126 non-null  float64
 6   cart_size     44909 non-null   float64
 7   payment       33580 non-null   object
 8   discount_pct  33580 non-null   float64
 9   amount_usd    33580 non-null   float64
dtypes: float64(5), int64(2), object(3)
memory usage: 58.1+ MB

In [ ]:
events_df['timestamp'] = pd.to_datetime(events_df['timestamp'], errors='coerce')

In [ ]:
events_df['event_date'] = events_df['timestamp'].dt.date

In [ ]:
events_df['event_time'] = events_df['timestamp'].dt.time

In [ ]:
events_df.dtypes

event_id                 int64
session_id               int64
timestamp       datetime64[ns]
event_type              object
product_id             float64
qty                    float64
cart_size              float64
payment                 object
discount_pct           float64
amount_usd             float64
event_date              object
event_time              object
dtype: object

In [ ]:
events_df[['timestamp', 'event_date', 'event_time']].head()

            timestamp  event_date event_time
0 2021-12-27 00:08:36  2021-12-27   00:08:36
1 2021-12-27 00:16:36  2021-12-27   00:16:36
2 2021-12-27 00:18:01  2021-12-27   00:18:01
3 2021-12-27 00:45:36  2021-12-27   00:45:36
4 2021-12-27 01:03:36  2021-12-27   01:03:36

In [ ]:
events_df = events_df.drop(columns=['timestamp'])

In [ ]:
events_df.head()

,event_id,session_id,event_type,product_id,qty,cart_size,payment,discount_pct,amount_usd,event_date,event_time
0,1,1,page_view,93.0,NaN,NaN,NaN,NaN,NaN,2021-12-27,00:08:36
1,2,1,page_view,1005.0,NaN,NaN,NaN,NaN,NaN,2021-12-27,00:16:36
2,3,1,add_to_cart,1005.0,1.0,NaN,NaN,NaN,NaN,2021-12-27,00:18:01
3,4,1,page_view,918.0,NaN,NaN,NaN,NaN,NaN,2021-12-27,00:45:36
4,5,1,page_view,946.0,NaN,NaN,NaN,NaN,NaN,2021-12-27,01:03:36

In [ ]:
print (events_df.count () )

event_id        760958
session_id      760958
event_type      760958
product_id      682469
qty             143126
cart_size        44909
payment          33580
discount_pct     33580
amount_usd       33580
event_date      760958
event_time      760958
dtype: int64

In [ ]:
events_df.describe()

,event_id,session_id,product_id,qty,cart_size,discount_pct,amount_usd
count,760958.000000,760958.000000,682469.000000,143126.000000,44909.000000,33580.000000,33580.000000
mean,380479.500000,60153.502012,652.313074,1.301748,2.286958,7.160214,133.806357
std,219669.797409,34613.117088,340.279129,0.783436,1.612397,7.474901,152.130611
min,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,2.800000
25%,190240.250000,30314.250000,368.000000,1.000000,1.000000,0.000000,40.300000
50%,380479.500000,60176.000000,674.000000,1.000000,2.000000,5.000000,86.460000
75%,570718.750000,90110.000000,954.000000,1.000000,3.000000,15.000000,174.270000
max,760958.000000,120000.000000,1197.000000,4.000000,13.000000,20.000000,2984.580000

In [ ]:
#shows the number of null values in the dataframe
print("Number of NaN values for each columns: ")
events_df.isna().sum()

Number of NaN values for each columns:

event_id             0
session_id           0
event_type           0
product_id       78489
qty             617832
cart_size       716049
payment         727378
discount_pct    727378
amount_usd      727378
event_date           0
event_time           0
dtype: int64

*NaN values are retained because they are expected based on different customer event types (e.g., page_view, add_to_cart, purchase).*

In [ ]:
#Check duplicate
events_df.duplicated().sum()

np.int64(0)

Validate categorical column in event_df

In [ ]:
events_df['event_type'].value_counts()

event_type
page_view      539343
add_to_cart    143126
checkout        44909
purchase        33580
Name: count, dtype: int64

# Analyse orderItems Dataset

In [ ]:
orderItems_df.head(10)

   order_id  product_id  unit_price_usd  quantity  line_total_usd
0         1         226          107.15         1          107.15
1         2         771          116.17         1          116.17
2         3         415           94.49         1           94.49
3         3          24           42.86         1           42.86
4         4        1157           32.18         1           32.18
5         5         846           39.60         1           39.60
6         5         745          198.49         1          198.49
7         6         123           81.79         1           81.79
8         6         888           47.85         1           47.85
9         7         405            5.63         1            5.63

In [ ]:
orderItems_df.shape

(59163, 5)

In [ ]:
orderItems_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59163 entries, 0 to 59162
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        59163 non-null  int64
 1   product_id      59163 non-null  int64
 2   unit_price_usd  59163 non-null  float64
 3   quantity        59163 non-null  int64
 4   line_total_usd  59163 non-null  float64
dtypes: float64(2), int64(3)
memory usage: 2.3 MB

In [ ]:
print(orderItems_df.columns.values)

['order_id' 'product_id' 'unit_price_usd' 'quantity' 'line_total_usd']

In [ ]:
#showing the datatypes of the column
orderItems_df.dtypes

order_id            int64
product_id          int64
unit_price_usd    float64
quantity            int64
line_total_usd    float64
dtype: object

In [ ]:
print(orderItems_df.count())

order_id          59163
product_id        59163
unit_price_usd    59163
quantity          59163
line_total_usd    59163
dtype: int64

In [ ]:
#describe the dataframe with showing the count, mean, standard deviation, min, percentiles, and max.
orderItems_df.describe()

,order_id,product_id,unit_price_usd,quantity,line_total_usd
count,59163.000000,59163.000000,59163.000000,59163.000000,59163.000000
mean,16811.777868,692.100147,62.837561,1.303281,81.733655
std,9687.818391,329.197199,62.061297,0.786787,106.360939
min,1.000000,1.000000,3.500000,1.000000,3.500000
25%,8454.000000,411.000000,21.640000,1.000000,24.770000
50%,16838.000000,738.000000,44.650000,1.000000,49.920000
75%,25203.000000,980.000000,79.450000,1.000000,98.680000
max,33580.000000,1197.000000,596.620000,4.000000,2376.920000

In [ ]:
#shows the number of null values in the dataframe
print("Number of NaN values for each columns: ")
orderItems_df.isna().sum()

Number of NaN values for each columns:

order_id          0
product_id        0
unit_price_usd    0
quantity          0
line_total_usd    0
dtype: int64

In [ ]:
#Check duplicate
orderItems_df.duplicated().sum()

np.int64(73)

In [ ]:
#drop duplicates
orderItems_df= orderItems_df.drop_duplicates()

In [ ]:
#Reheck duplicate
orderItems_df.duplicated().sum()

np.int64(0)

In [ ]:
orderItems_df.head()

   order_id  product_id  unit_price_usd  quantity  line_total_usd
0         1         226          107.15         1          107.15
1         2         771          116.17         1          116.17
2         3         415           94.49         1           94.49
3         3          24           42.86         1           42.86
4         4        1157           32.18         1           32.18

# Analyse orders Dataset

In [ ]:
orders_df.head(10)

,order_id,customer_id,order_time,payment_method,discount_pct,subtotal_usd,total_usd,country,device,source
0,1,13917,2025-01-31T23:07:42,card,20,107.15,85.72,PL,desktop,organic
1,2,1022,2024-02-19T01:17:50,card,0,116.17,116.17,FR,tablet,organic
2,3,6145,2024-12-04T20:24:13,card,0,137.35,137.35,US,mobile,organic
3,4,3152,2024-07-17T08:50:47,card,15,32.18,27.35,BR,mobile,email
4,5,12378,2020-08-21T16:54:16,card,0,238.09,238.09,NL,desktop,paid
5,6,18712,2022-03-07T03:42:34,paypal,0,129.64,129.64,GB,mobile,paid
6,7,17224,2020-03-15T08:56:46,wallet,15,145.45,123.63,JP,mobile,paid
7,8,3448,2021-12-06T01:26:52,card,0,9.03,9.03,JP,desktop,direct
8,9,9132,2022-11-28T03:34:04,card,20,392.95,314.36,IN,mobile,direct
9,10,14764,2023-03-15T10:06:17,paypal,20,9.69,7.75,ES,mobile,organic

In [ ]:
orders_df.shape

(33580, 10)

In [ ]:
print(orders_df.columns.values)

['order_id' 'customer_id' 'order_time' 'payment_method' 'discount_pct'
 'subtotal_usd' 'total_usd' 'country' 'device' 'source']

In [ ]:
orders_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33580 entries, 0 to 33579
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        33580 non-null  int64
 1   customer_id     33580 non-null  int64
 2   order_time      33580 non-null  object
 3   payment_method  33580 non-null  object
 4   discount_pct    33580 non-null  int64
 5   subtotal_usd    33580 non-null  float64
 6   total_usd       33580 non-null  float64
 7   country         33580 non-null  object
 8   device          33580 non-null  object
 9   source          33580 non-null  object
dtypes: float64(2), int64(3), object(5)
memory usage: 2.6+ MB

In [ ]:
# saparate [order_time] to date and time

orders_df['order_time'] = pd.to_datetime(orders_df['order_time'] )

In [ ]:
orders_df['order_date'] = orders_df['order_time'].dt.date

In [ ]:
orders_df['order_time'] = orders_df['order_time'].dt.time

In [ ]:
orders_df[['order_date', 'order_time']].head()

   order_date order_time
0  2025-01-31   23:07:42
1  2024-02-19   01:17:50
2  2024-12-04   20:24:13
3  2024-07-17   08:50:47
4  2020-08-21   16:54:16

In [ ]:
events_df.columns

Index(['event_id', 'session_id', 'event_type', 'product_id', 'qty',
       'cart_size', 'payment', 'discount_pct', 'amount_usd', 'event_date',
       'event_time'],
      dtype='object')

In [ ]:
orders_df.head()

,order_id,customer_id,order_time,payment_method,discount_pct,subtotal_usd,total_usd,country,device,source,order_date
0,1,13917,23:07:42,card,20,107.15,85.72,PL,desktop,organic,2025-01-31
1,2,1022,01:17:50,card,0,116.17,116.17,FR,tablet,organic,2024-02-19
2,3,6145,20:24:13,card,0,137.35,137.35,US,mobile,organic,2024-12-04
3,4,3152,08:50:47,card,15,32.18,27.35,BR,mobile,email,2024-07-17
4,5,12378,16:54:16,card,0,238.09,238.09,NL,desktop,paid,2020-08-21

In [ ]:
orders_df = orders_df[[
    'order_id', 'customer_id', 'order_time', 'order_date',
    'payment_method', 'discount_pct', 'subtotal_usd',
    'total_usd', 'country', 'device', 'source'
]]

In [ ]:
print(orders_df.columns.values)

['order_id' 'customer_id' 'order_time' 'order_date' 'payment_method'
 'discount_pct' 'subtotal_usd' 'total_usd' 'country' 'device' 'source']

In [ ]:

#describe the dataframe with showing the count, mean, standard deviation, min, percentiles, and max.
orders_df.describe()

           order_id   customer_id  discount_pct  subtotal_usd     total_usd
count  33580.000000  33580.000000  33580.000000  33580.000000  33580.000000
mean   16790.500000  10010.629899      7.160214    144.002627    133.806357
std     9693.855356   5798.458913      7.474901    162.603585    152.130611
min        1.000000      1.000000      0.000000      3.500000      2.800000
25%     8395.750000   4964.000000      0.000000     44.060000     40.300000
50%    16790.500000  10008.000000      5.000000     93.620000     86.460000
75%    25185.250000  15061.000000     15.000000    187.100000    174.270000
max    33580.000000  19999.000000     20.000000   3141.660000   2984.580000

Check Null Value and duplicate

In [ ]:
#shows the number of null values in the dataframe
print("Number of NaN values for each columns: ")
orders_df.isna().sum()

Number of NaN values for each columns:

order_id          0
customer_id       0
order_time        0
order_date        0
payment_method    0
discount_pct      0
subtotal_usd      0
total_usd         0
country           0
device            0
source            0
dtype: int64

In [ ]:
#Check duplicate
orders_df.duplicated().sum()

np.int64(0)

Validate categorical column in customers_df

In [ ]:
orders_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33580 entries, 0 to 33579
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        33580 non-null  int64
 1   customer_id     33580 non-null  int64
 2   order_time      33580 non-null  object
 3   order_date      33580 non-null  object
 4   payment_method  33580 non-null  object
 5   discount_pct    33580 non-null  int64
 6   subtotal_usd    33580 non-null  float64
 7   total_usd       33580 non-null  float64
 8   country         33580 non-null  object
 9   device          33580 non-null  object
 10  source          33580 non-null  object
dtypes: float64(2), int64(3), object(6)
memory usage: 2.8+ MB

In [ ]:
orders_df['payment_method'].value_counts()

payment_method
card      23455
paypal     5032
wallet     3373
cod        1720
Name: count, dtype: int64

In [ ]:
orders_df['device'].value_counts()

device
mobile     18469
desktop    12750
tablet      2361
Name: count, dtype: int64

In [ ]:
orders_df['source'].value_counts()

source
organic     11268
direct       8387
paid         4121
social       4024
email        3056
referral     2724
Name: count, dtype: int64

In [ ]:
#Check total number of country
orders_df['country'].nunique()

17

total country same as pervious datasets

In [ ]:
orders_df['country'].value_counts()

country
US    6138
GB    2653
IN    2642
BR    2464
DE    2321
FR    2188
MX    2022
AU    1797
JP    1655
CA    1651
ES    1558
NL    1491
SG    1379
SE    1029
PL    1014
AE     913
ZA     665
Name: count, dtype: int64

country name in shortforms

In [ ]:
#change country name to its full name
#based on previous country_map
print(country_map)

{'AE': 'United Arab Emirates', 'AU': 'Australia', 'BR': 'Brazil', 'CA': 'Canada', 'DE': 'Germany', 'ES': 'Spain', 'FR': 'France', 'GB': 'United Kingdom', 'IN': 'India', 'JP': 'Japan', 'MX': 'Mexico', 'NL': 'Netherlands', 'PL': 'Poland', 'SE': 'Sweden', 'SG': 'Singapore', 'US': 'United States', 'ZA': 'South Africa'}

In [ ]:
orders_df['country'] = orders_df['country'].map(country_map)

In [ ]:
orders_df['country'].value_counts()

country
United States           6138
United Kingdom          2653
India                   2642
Brazil                  2464
Germany                 2321
France                  2188
Mexico                  2022
Australia               1797
Japan                   1655
Canada                  1651
Spain                   1558
Netherlands             1491
Singapore               1379
Sweden                  1029
Poland                  1014
United Arab Emirates     913
South Africa             665
Name: count, dtype: int64

In [ ]:
orders_df.head()

,order_id,customer_id,order_time,order_date,payment_method,discount_pct,subtotal_usd,total_usd,country,device,source
0,1,13917,23:07:42,2025-01-31,card,20,107.15,85.72,Poland,desktop,organic
1,2,1022,01:17:50,2024-02-19,card,0,116.17,116.17,France,tablet,organic
2,3,6145,20:24:13,2024-12-04,card,0,137.35,137.35,United States,mobile,organic
3,4,3152,08:50:47,2024-07-17,card,15,32.18,27.35,Brazil,mobile,email
4,5,12378,16:54:16,2020-08-21,card,0,238.09,238.09,Netherlands,desktop,paid

# Analyse products Dataset

In [ ]:
products_df.head(10)

,product_id,category,name,price_usd,cost_usd,margin_usd
0,1,Electronics,SSD MediumBlue 149,570.28,352.69,217.59
1,2,Electronics,Keyboard DeepPink 696,498.13,263.13,235.00
2,3,Electronics,Headphones Orchid 188,548.53,309.60,238.93
3,4,Electronics,Smartwatch BurlyWood 664,268.36,153.56,114.80
4,5,Electronics,Smartwatch Cornsilk 328,63.69,42.65,21.04
5,6,Electronics,Headphones WhiteSmoke 326,358.95,222.19,136.76
6,7,Electronics,Headphones DarkGray 529,347.30,187.53,159.77
7,8,Electronics,Mouse Moccasin 673,338.19,227.02,111.17
8,9,Electronics,Mouse Chartreuse 292,88.74,59.58,29.16
9,10,Electronics,SSD Tan 677,85.54,61.04,24.50

In [ ]:
products_df.shape

(1197, 6)

In [ ]:
print(products_df.columns.values)

['product_id' 'category' 'name' 'price_usd' 'cost_usd' 'margin_usd']

In [ ]:
products_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1197 entries, 0 to 1196
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   product_id  1197 non-null   int64
 1   category    1197 non-null   object
 2   name        1197 non-null   object
 3   price_usd   1197 non-null   float64
 4   cost_usd    1197 non-null   float64
 5   margin_usd  1197 non-null   float64
dtypes: float64(3), int64(1), object(2)
memory usage: 56.2+ KB

In [ ]:
print(products_df.count())

product_id    1197
category      1197
name          1197
price_usd     1197
cost_usd      1197
margin_usd    1197
dtype: int64

In [ ]:
products_df.describe()

        product_id    price_usd     cost_usd   margin_usd
count  1197.000000  1197.000000  1197.000000  1197.000000
mean    599.000000   119.935171    77.626483    42.308688
std     345.688444   119.681742    79.228858    44.464057
min       1.000000     3.500000     2.210000     1.030000
25%     300.000000    38.540000    23.530000    12.240000
50%     599.000000    77.200000    49.140000    27.020000
75%     898.000000   165.420000   103.670000    55.440000
max    1197.000000   596.620000   446.100000   263.730000

Check null value and duplicates

In [ ]:
#shows the number of null values in the dataframe
print("Number of NaN values for each columns: ")
products_df.isna().sum()

Number of NaN values for each columns:

product_id    0
category      0
name          0
price_usd     0
cost_usd      0
margin_usd    0
dtype: int64

In [ ]:
#Check duplicate
products_df.duplicated().sum()

np.int64(0)

Validate categorical column

In [ ]:
products_df['category'].value_counts()

category
Electronics       171
Home & Kitchen    171
Beauty            171
Sports            171
Fashion           171
Books             171
Toys              171
Name: count, dtype: int64

In [ ]:
products_df['name'].nunique()

1197

the product name is unique

In [ ]:
products_df.head()

,product_id,category,name,price_usd,cost_usd,margin_usd
0,1,Electronics,SSD MediumBlue 149,570.28,352.69,217.59
1,2,Electronics,Keyboard DeepPink 696,498.13,263.13,235.00
2,3,Electronics,Headphones Orchid 188,548.53,309.60,238.93
3,4,Electronics,Smartwatch BurlyWood 664,268.36,153.56,114.80
4,5,Electronics,Smartwatch Cornsilk 328,63.69,42.65,21.04

# Analyse reviews Dataset

In [ ]:
reviews_df.head(10)

,review_id,order_id,product_id,rating,review_text,review_time
0,1,4,1157,2,Not great quality.,2022-02-01T00:00:00
1,2,7,405,4,Good value for money!,2020-03-07T00:00:00
2,3,7,487,5,"Excellent product, highly recommend!",2024-12-26T00:00:00
3,4,7,442,5,"Excellent product, highly recommend!",2021-03-18T00:00:00
4,5,7,348,4,Good value for money!,2025-09-30T00:00:00
5,6,23,1018,4,Good value for money!,2021-12-11T00:00:00
6,7,33,769,2,Not great quality.,2021-06-04T00:00:00
7,8,36,602,4,Good value for money!,2025-07-10T00:00:00
8,9,36,351,5,"Excellent product, highly recommend!",2020-05-08T00:00:00
9,10,49,501,3,Okay overall.,2023-02-12T00:00:00

In [ ]:
reviews_df.shape

(10780, 6)

In [ ]:
reviews_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10780 entries, 0 to 10779
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   review_id    10780 non-null  int64
 1   order_id     10780 non-null  int64
 2   product_id   10780 non-null  int64
 3   rating       10780 non-null  int64
 4   review_text  10780 non-null  object
 5   review_time  10780 non-null  object
dtypes: int64(4), object(2)
memory usage: 505.4+ KB

In [ ]:
reviews_df['review_time'] = pd.to_datetime(reviews_df['review_time'])

In [ ]:
reviews_df['review_date'] = reviews_df['review_time'].dt.date

In [ ]:
reviews_df['review_time'] = reviews_df['review_time'].dt.time

In [ ]:
reviews_df[['review_date', 'review_time']].head()

  review_date review_time
0  2022-02-01    00:00:00
1  2020-03-07    00:00:00
2  2024-12-26    00:00:00
3  2021-03-18    00:00:00
4  2025-09-30    00:00:00

In [ ]:
reviews_df.head(10)

,review_id,order_id,product_id,rating,review_text,review_time,review_date
0,1,4,1157,2,Not great quality.,00:00:00,2022-02-01
1,2,7,405,4,Good value for money!,00:00:00,2020-03-07
2,3,7,487,5,"Excellent product, highly recommend!",00:00:00,2024-12-26
3,4,7,442,5,"Excellent product, highly recommend!",00:00:00,2021-03-18
4,5,7,348,4,Good value for money!,00:00:00,2025-09-30
5,6,23,1018,4,Good value for money!,00:00:00,2021-12-11
6,7,33,769,2,Not great quality.,00:00:00,2021-06-04
7,8,36,602,4,Good value for money!,00:00:00,2025-07-10
8,9,36,351,5,"Excellent product, highly recommend!",00:00:00,2020-05-08
9,10,49,501,3,Okay overall.,00:00:00,2023-02-12

In [ ]:
reviews_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10780 entries, 0 to 10779
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   review_id    10780 non-null  int64
 1   order_id     10780 non-null  int64
 2   product_id   10780 non-null  int64
 3   rating       10780 non-null  int64
 4   review_text  10780 non-null  object
 5   review_time  10780 non-null  object
 6   review_date  10780 non-null  object
dtypes: int64(4), object(3)
memory usage: 589.7+ KB

In [ ]:
reviews_df['review_date'] = pd.to_datetime(reviews_df['review_date'])

In [ ]:
reviews_df.dtypes

review_id               int64
order_id                int64
product_id              int64
rating                  int64
review_text            object
review_time            object
review_date    datetime64[ns]
dtype: object

Check Null Value and duplicates

In [ ]:
#shows the number of null values in the dataframe
print("Number of NaN values for each columns: ")
reviews_df.isna().sum()

Number of NaN values for each columns:

review_id      0
order_id       0
product_id     0
rating         0
review_text    0
review_time    0
review_date    0
dtype: int64

In [ ]:
#Check duplicate
reviews_df.duplicated().sum()

np.int64(0)

**Validate categorical dataframe**

In [ ]:
reviews_df['rating'].value_counts()

rating
5    4055
4    3565
3    1980
2     757
1     423
Name: count, dtype: int64

the rating for reviews is 1-5

# Hackathon Question

- Analyze User Behavior & Transactions
  - Process user interactions, browsing patterns, and purchase history in real-time
- Predict Cart Abandonment
  - Identify users likely to drop off using behavioral patterns and predictive models
- Recommend Next Best Products
  - Suggest personalized products based on user activity and preferences

# Analyze User Behavior & Transactions

### **Merge Dataframe**

In [ ]:
behavior_df = (
    events_df
    .merge(session_df, on="session_id", how="left", suffixes=("_event", "_session"))
    .merge(customers_df, on="customer_id", how="left")
    .merge(products_df, on="product_id", how="left")
)

In [ ]:
behavior_df.head()

,event_id,session_id,event_type,product_id,qty,cart_size,payment,discount_pct,amount_usd,event_date,...,country_y,age,age_group,signup_date,marketing_opt_in,category,name_y,price_usd,cost_usd,margin_usd
0,1,1,page_view,93.0,NaN,NaN,NaN,NaN,NaN,2021-12-27,...,Germany,43,Mid Age (36-50 Years Old),2024-08-12,Unsubscribed,Electronics,Headphones Snow 402,249.08,163.20,85.88
1,2,1,page_view,1005.0,NaN,NaN,NaN,NaN,NaN,2021-12-27,...,Germany,43,Mid Age (36-50 Years Old),2024-08-12,Unsubscribed,Books,E-book Blue 118,6.43,4.16,2.27
2,3,1,add_to_cart,1005.0,1.0,NaN,NaN,NaN,NaN,2021-12-27,...,Germany,43,Mid Age (36-50 Years Old),2024-08-12,Unsubscribed,Books,E-book Blue 118,6.43,4.16,2.27
3,4,1,page_view,918.0,NaN,NaN,NaN,NaN,NaN,2021-12-27,...,Germany,43,Mid Age (36-50 Years Old),2024-08-12,Unsubscribed,Books,E-book DeepPink 346,31.71,19.44,12.27
4,5,1,page_view,946.0,NaN,NaN,NaN,NaN,NaN,2021-12-27,...,Germany,43,Mid Age (36-50 Years Old),2024-08-12,Unsubscribed,Books,E-book RosyBrown 381,11.39,8.15,3.24

In [ ]:
order_summary = (
    orders_df.groupby("customer_id", as_index=False)
    .agg(
        total_orders=("order_id", "nunique"),
        total_spent=("total_usd", "sum"),
        last_order_time=("order_time", "max")
    )
)

In [ ]:
order_summary

       customer_id  total_orders  total_spent last_order_time
0                1             2       115.39        16:02:53
1                2             2        68.52        17:48:30
2                3             1        66.72        07:39:11
3                4             2       279.86        03:07:16
4                5             3       271.29        21:36:57
...            ...           ...          ...             ...
16263        19993             3       670.67        11:44:48
16264        19994             1       263.30        16:48:12
16265        19996             1        65.53        18:42:19
16266        19998             4       568.55        23:42:25
16267        19999             2        57.36        18:50:53

[16268 rows x 4 columns]

In [ ]:
behavior_transactions_df = behavior_df.merge(order_summary, on="customer_id", how="left")

In [ ]:
behavior_transactions_df.head(20)

,event_id,session_id,event_type,product_id,qty,cart_size,payment,discount_pct,amount_usd,event_date,...,signup_date,marketing_opt_in,category,name_y,price_usd,cost_usd,margin_usd,total_orders,total_spent,last_order_time
0,1,1,page_view,93.0,NaN,NaN,NaN,NaN,NaN,2021-12-27,...,2024-08-12,Unsubscribed,Electronics,Headphones Snow 402,249.08,163.20,85.88,3.0,619.23,14:23:50
1,2,1,page_view,1005.0,NaN,NaN,NaN,NaN,NaN,2021-12-27,...,2024-08-12,Unsubscribed,Books,E-book Blue 118,6.43,4.16,2.27,3.0,619.23,14:23:50
2,3,1,add_to_cart,1005.0,1.0,NaN,NaN,NaN,NaN,2021-12-27,...,2024-08-12,Unsubscribed,Books,E-book Blue 118,6.43,4.16,2.27,3.0,619.23,14:23:50
3,4,1,page_view,918.0,NaN,NaN,NaN,NaN,NaN,2021-12-27,...,2024-08-12,Unsubscribed,Books,E-book DeepPink 346,31.71,19.44,12.27,3.0,619.23,14:23:50
4,5,1,page_view,946.0,NaN,NaN,NaN,NaN,NaN,2021-12-27,...,2024-08-12,Unsubscribed,Books,E-book RosyBrown 381,11.39,8.15,3.24,3.0,619.23,14:23:50
5,6,1,add_to_cart,946.0,1.0,NaN,NaN,NaN,NaN,2021-12-27,...,2024-08-12,Unsubscribed,Books,E-book RosyBrown 381,11.39,8.15,3.24,3.0,619.23,14:23:50
6,7,1,page_view,915.0,NaN,NaN,NaN,NaN,NaN,2021-12-27,...,2024-08-12,Unsubscribed,Books,Paperback Gainsboro 494,48.73,30.02,18.71,3.0,619.23,14:23:50
7,8,1,page_view,931.0,NaN,NaN,NaN,NaN,NaN,2021-12-27,...,2024-08-12,Unsubscribed,Books,Hardcover Coral 875,49.97,25.97,24.00,3.0,619.23,14:23:50
8,9,1,add_to_cart,931.0,1.0,NaN,NaN,NaN,NaN,2021-12-27,...,2024-08-12,Unsubscribed,Books,Hardcover Coral 875,49.97,25.97,24.00,3.0,619.23,14:23:50
9,10,1,page_view,978.0,NaN,NaN,NaN,NaN,NaN,2021-12-27,...,2024-08-12,Unsubscribed,Books,E-book Lavender 920,30.44,18.56,11.88,3.0,619.23,14:23:50
10,11,2,page_view,929.0,NaN,NaN,NaN,NaN,NaN,2025-01-31,...,2025-07-09,Subscribed,Books,Paperback LightBlue 978,15.33,11.53,3.80,1.0,85.72,23:07:42
11,12,2,page_view,226.0,NaN,NaN,NaN,NaN,NaN,2025-01-31,...,2025-07-09,Subscribed,Home & Kitchen,Toaster MediumSlateBlue 575,107.15,65.65,41.50,1.0,85.72,23:07:42
12,13,2,add_to_cart,226.0,1.0,NaN,NaN,NaN,NaN,2025-01-31,...,2025-07-09,Subscribed,Home & Kitchen,Toaster MediumSlateBlue 575,107.15,65.65,41.50,1.0,85.72,23:07:42
13,14,2,page_view,864.0,NaN,NaN,NaN,NaN,NaN,2025-01-31,...,2025-07-09,Subscribed,Books,E-book HoneyDew 688,10.21,8.11,2.10,1.0,85.72,23:07:42
14,15,2,page_view,1151.0,NaN,NaN,NaN,NaN,NaN,2025-01-31,...,2025-07-09,Subscribed,Toys,Puzzle OldLace 463,9.27,5.12,4.15,1.0,85.72,23:07:42
15,16,2,page_view,855.0,NaN,NaN,NaN,NaN,NaN,2025-01-31,...,2025-07-09,Subscribed,Fashion,Dress FloralWhite 158,138.36,83.20,55.16,1.0,85.72,23:07:42
16,17,2,checkout,NaN,NaN,1.0,NaN,NaN,NaN,2025-01-31,...,2025-07-09,Subscribed,NaN,NaN,NaN,NaN,NaN,1.0,85.72,23:07:42
17,18,2,purchase,NaN,NaN,NaN,card,20.0,85.72,2025-01-31,...,2025-07-09,Subscribed,NaN,NaN,NaN,NaN,NaN,1.0,85.72,23:07:42
18,19,3,page_view,771.0,NaN,NaN,NaN,NaN,NaN,2024-02-19,...,2023-03-31,Unsubscribed,Fashion,Socks Orange 300,116.17,70.22,45.95,2.0,329.33,11:45:08
19,20,3,add_to_cart,771.0,1.0,NaN,NaN,NaN,NaN,2024-02-19,...,2023-03-31,Unsubscribed,Fashion,Socks Orange 300,116.17,70.22,45.95,2.0,329.33,11:45:08

In [ ]:
# Validate key relationship
behavior_transactions_df.groupby('session_id')['customer_id'].nunique().max()

1

1 session = 1 user

In [ ]:
#Check missing value
behavior_transactions_df.isnull().sum()

event_id                 0
session_id               0
event_type               0
product_id           78489
qty                 617832
cart_size           716049
payment             727378
discount_pct        727378
amount_usd          727378
event_date               0
event_time               0
customer_id              0
device                   0
source                   0
country_x                0
session_date             0
session_time             0
name_x                   0
email                    0
country_y                0
age                      0
age_group                0
signup_date              0
marketing_opt_in         0
category             78489
name_y               78489
price_usd            78489
cost_usd             78489
margin_usd           78489
total_orders         86320
total_spent          86320
last_order_time      86320
dtype: int64

*Missing* values were expected due to the event-driven nature of the dataset, where attributes such as quantity and transaction value are only applicable to specific event types.

In [ ]:
# Check duplicate
behavior_transactions_df.duplicated().sum()

np.int64(0)

no duplicates in this merge file

In [ ]:
behavior_transactions_df['session_id'].duplicated().sum()

np.int64(640958)

1 session → many events

In [ ]:
behavior_transactions_df['session_id'].value_counts().head()

session_id
8287      17
84620     17
119546    17
81630     17
9118      17
Name: count, dtype: int64

In [ ]:
behavior_transactions_df[['session_id','customer_id']].head()

   session_id  customer_id
0           1        12360
1           1        12360
2           1        12360
3           1        12360
4           1        12360

In [ ]:
behavior_transactions_df.columns

Index(['event_id', 'session_id', 'event_type', 'product_id', 'qty',
       'cart_size', 'payment', 'discount_pct', 'amount_usd', 'event_date',
       'event_time', 'customer_id', 'device', 'source', 'country_x',
       'session_date', 'session_time', 'name_x', 'email', 'country_y', 'age',
       'age_group', 'signup_date', 'marketing_opt_in', 'category', 'name_y',
       'price_usd', 'cost_usd', 'margin_usd', 'total_orders', 'total_spent',
       'last_order_time'],
      dtype='object')

# Check column issues (_x, _y)

In [ ]:
behavior_transactions_df.columns

Index(['event_id', 'session_id', 'event_type', 'product_id', 'qty',
       'cart_size', 'payment', 'discount_pct', 'amount_usd', 'event_date',
       'event_time', 'customer_id', 'device', 'source', 'country_x',
       'session_date', 'session_time', 'name_x', 'email', 'country_y', 'age',
       'age_group', 'signup_date', 'marketing_opt_in', 'category', 'name_y',
       'price_usd', 'cost_usd', 'margin_usd', 'total_orders', 'total_spent',
       'last_order_time'],
      dtype='object')

In [ ]:
# Validate data consistency
behavior_transactions_df[['country_x','country_y']].head()

  country_x country_y
0   Germany   Germany
1   Germany   Germany
2   Germany   Germany
3   Germany   Germany
4   Germany   Germany

In [ ]:
behavior_transactions_df = behavior_transactions_df.drop(columns=['country_y'])
behavior_transactions_df = behavior_transactions_df.rename(columns={'country_x': 'country'})

In [ ]:
behavior_transactions_df.head()

,event_id,session_id,event_type,product_id,qty,cart_size,payment,discount_pct,amount_usd,event_date,...,signup_date,marketing_opt_in,category,name_y,price_usd,cost_usd,margin_usd,total_orders,total_spent,last_order_time
0,1,1,page_view,93.0,NaN,NaN,NaN,NaN,NaN,2021-12-27,...,2024-08-12,Unsubscribed,Electronics,Headphones Snow 402,249.08,163.20,85.88,3.0,619.23,14:23:50
1,2,1,page_view,1005.0,NaN,NaN,NaN,NaN,NaN,2021-12-27,...,2024-08-12,Unsubscribed,Books,E-book Blue 118,6.43,4.16,2.27,3.0,619.23,14:23:50
2,3,1,add_to_cart,1005.0,1.0,NaN,NaN,NaN,NaN,2021-12-27,...,2024-08-12,Unsubscribed,Books,E-book Blue 118,6.43,4.16,2.27,3.0,619.23,14:23:50
3,4,1,page_view,918.0,NaN,NaN,NaN,NaN,NaN,2021-12-27,...,2024-08-12,Unsubscribed,Books,E-book DeepPink 346,31.71,19.44,12.27,3.0,619.23,14:23:50
4,5,1,page_view,946.0,NaN,NaN,NaN,NaN,NaN,2021-12-27,...,2024-08-12,Unsubscribed,Books,E-book RosyBrown 381,11.39,8.15,3.24,3.0,619.23,14:23:50

In [ ]:
behavior_transactions_df[['name_x','name_y']].head()

            name_x                name_y
0  Ronald Williams   Headphones Snow 402
1  Ronald Williams       E-book Blue 118
2  Ronald Williams       E-book Blue 118
3  Ronald Williams   E-book DeepPink 346
4  Ronald Williams  E-book RosyBrown 381

name_x = Customer name

name_y = Product name

In [ ]:
behavior_transactions_df = behavior_transactions_df.rename(columns={
    'name_x': 'customer_name',
    'name_y': 'product_name'
})

In [ ]:
behavior_transactions_df.head()

,event_id,session_id,event_type,product_id,qty,cart_size,payment,discount_pct,amount_usd,event_date,...,signup_date,marketing_opt_in,category,product_name,price_usd,cost_usd,margin_usd,total_orders,total_spent,last_order_time
0,1,1,page_view,93.0,NaN,NaN,NaN,NaN,NaN,2021-12-27,...,2024-08-12,Unsubscribed,Electronics,Headphones Snow 402,249.08,163.20,85.88,3.0,619.23,14:23:50
1,2,1,page_view,1005.0,NaN,NaN,NaN,NaN,NaN,2021-12-27,...,2024-08-12,Unsubscribed,Books,E-book Blue 118,6.43,4.16,2.27,3.0,619.23,14:23:50
2,3,1,add_to_cart,1005.0,1.0,NaN,NaN,NaN,NaN,2021-12-27,...,2024-08-12,Unsubscribed,Books,E-book Blue 118,6.43,4.16,2.27,3.0,619.23,14:23:50
3,4,1,page_view,918.0,NaN,NaN,NaN,NaN,NaN,2021-12-27,...,2024-08-12,Unsubscribed,Books,E-book DeepPink 346,31.71,19.44,12.27,3.0,619.23,14:23:50
4,5,1,page_view,946.0,NaN,NaN,NaN,NaN,NaN,2021-12-27,...,2024-08-12,Unsubscribed,Books,E-book RosyBrown 381,11.39,8.15,3.24,3.0,619.23,14:23:50

In [ ]:
behavior_transactions_df['event_type'].value_counts()

event_type
page_view      539343
add_to_cart    143126
checkout        44909
purchase        33580
Name: count, dtype: int64

In [ ]:
# behavior_transactions_df['event_type'] = behavior_transactions_df['event_type'].str.replace('_', ' ')

In [ ]:
behavior_transactions_df['event_type'].value_counts()

event_type
page_view      539343
add_to_cart    143126
checkout        44909
purchase        33580
Name: count, dtype: int64

In [ ]:
# check merge data type
behavior_transactions_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 760958 entries, 0 to 760957
Data columns (total 31 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   event_id          760958 non-null  int64
 1   session_id        760958 non-null  int64
 2   event_type        760958 non-null  object
 3   product_id        682469 non-null  float64
 4   qty               143126 non-null  float64
 5   cart_size         44909 non-null   float64
 6   payment           33580 non-null   object
 7   discount_pct      33580 non-null   float64
 8   amount_usd        33580 non-null   float64
 9   event_date        760958 non-null  object
 10  event_time        760958 non-null  object
 11  customer_id       760958 non-null  int64
 12  device            760958 non-null  object
 13  source            760958 non-null  object
 14  country           760958 non-null  object
 15  session_date      760958 non-null  object
 16  session_time      760958 non-null  object
 17  customer_name     760958 non-null  object
 18  email             760958 non-null  object
 19  age               760958 non-null  int64
 20  age_group         760958 non-null  category
 21  signup_date       760958 non-null  object
 22  marketing_opt_in  760958 non-null  object
 23  category          682469 non-null  object
 24  product_name      682469 non-null  object
 25  price_usd         682469 non-null  float64
 26  cost_usd          682469 non-null  float64
 27  margin_usd        682469 non-null  float64
 28  total_orders      674638 non-null  float64
 29  total_spent       674638 non-null  float64
 30  last_order_time   674638 non-null  object
dtypes: category(1), float64(10), int64(4), object(16)
memory usage: 174.9+ MB

**Rearrange Column name**

In [ ]:
behavior_transactions_df.columns.values

array(['event_id', 'session_id', 'event_type', 'product_id', 'qty',
       'cart_size', 'payment', 'discount_pct', 'amount_usd', 'event_date',
       'event_time', 'customer_id', 'device', 'source', 'country',
       'session_date', 'session_time', 'customer_name', 'email', 'age',
       'age_group', 'signup_date', 'marketing_opt_in', 'category',
       'product_name', 'price_usd', 'cost_usd', 'margin_usd',
       'total_orders', 'total_spent', 'last_order_time'], dtype=object)

In [ ]:
new_order = [
    # Customer
    'customer_id', 'customer_name', 'email', 'age' , 'age_group', 'country',

    # Session
    'session_id', 'device', 'source',

    # Event
    'event_id', 'event_type', 'event_date', 'event_time', 'session_date', 'session_time',

    # Product
    'product_id', 'product_name', 'category',

    # Transaction
    'qty', 'cart_size', 'price_usd', 'discount_pct', 'amount_usd', 'payment', 'last_order_time',

    # Metrics
    'cost_usd', 'margin_usd', 'total_orders', 'total_spent',

    # Marketing
    'marketing_opt_in', 'signup_date'
]

behavior_transactions_df = behavior_transactions_df[new_order]

In [ ]:
behavior_transactions_df.columns.values

array(['customer_id', 'customer_name', 'email', 'age', 'age_group',
       'country', 'session_id', 'device', 'source', 'event_id',
       'event_type', 'event_date', 'event_time', 'session_date',
       'session_time', 'product_id', 'product_name', 'category', 'qty',
       'cart_size', 'price_usd', 'discount_pct', 'amount_usd', 'payment',
       'last_order_time', 'cost_usd', 'margin_usd', 'total_orders',
       'total_spent', 'marketing_opt_in', 'signup_date'], dtype=object)

In [ ]:
# check value distribution (SANITY CHECK)
behavior_transactions_df['device'].value_counts()

device
mobile     418289
desktop    289062
tablet      53607
Name: count, dtype: int64

In [ ]:
behavior_transactions_df['source'].value_counts()

source
organic     257354
direct      190197
paid         91985
social       91813
email        69102
referral     60507
Name: count, dtype: int64

In [ ]:
behavior_transactions_df['event_type'].value_counts()

event_type
page_view      539343
add_to_cart    143126
checkout        44909
purchase        33580
Name: count, dtype: int64

In [ ]:
# check unique count
behavior_transactions_df['session_id'].nunique()

120000

In [ ]:
behavior_transactions_df['customer_id'].nunique()

19945

In [ ]:
behavior_transactions_df['product_id'].nunique()

1197

In [ ]:
behavior_transactions_df.head(10)

,customer_id,customer_name,email,age,age_group,country,session_id,device,source,event_id,...,discount_pct,amount_usd,payment,last_order_time,cost_usd,margin_usd,total_orders,total_spent,marketing_opt_in,signup_date
0,12360,Ronald Williams,angelicamelton@example.net,43,Mid Age (36-50 Years Old),Germany,1,mobile,email,1,...,NaN,NaN,NaN,14:23:50,163.20,85.88,3.0,619.23,Unsubscribed,2024-08-12
1,12360,Ronald Williams,angelicamelton@example.net,43,Mid Age (36-50 Years Old),Germany,1,mobile,email,2,...,NaN,NaN,NaN,14:23:50,4.16,2.27,3.0,619.23,Unsubscribed,2024-08-12
2,12360,Ronald Williams,angelicamelton@example.net,43,Mid Age (36-50 Years Old),Germany,1,mobile,email,3,...,NaN,NaN,NaN,14:23:50,4.16,2.27,3.0,619.23,Unsubscribed,2024-08-12
3,12360,Ronald Williams,angelicamelton@example.net,43,Mid Age (36-50 Years Old),Germany,1,mobile,email,4,...,NaN,NaN,NaN,14:23:50,19.44,12.27,3.0,619.23,Unsubscribed,2024-08-12
4,12360,Ronald Williams,angelicamelton@example.net,43,Mid Age (36-50 Years Old),Germany,1,mobile,email,5,...,NaN,NaN,NaN,14:23:50,8.15,3.24,3.0,619.23,Unsubscribed,2024-08-12
5,12360,Ronald Williams,angelicamelton@example.net,43,Mid Age (36-50 Years Old),Germany,1,mobile,email,6,...,NaN,NaN,NaN,14:23:50,8.15,3.24,3.0,619.23,Unsubscribed,2024-08-12
6,12360,Ronald Williams,angelicamelton@example.net,43,Mid Age (36-50 Years Old),Germany,1,mobile,email,7,...,NaN,NaN,NaN,14:23:50,30.02,18.71,3.0,619.23,Unsubscribed,2024-08-12
7,12360,Ronald Williams,angelicamelton@example.net,43,Mid Age (36-50 Years Old),Germany,1,mobile,email,8,...,NaN,NaN,NaN,14:23:50,25.97,24.00,3.0,619.23,Unsubscribed,2024-08-12
8,12360,Ronald Williams,angelicamelton@example.net,43,Mid Age (36-50 Years Old),Germany,1,mobile,email,9,...,NaN,NaN,NaN,14:23:50,25.97,24.00,3.0,619.23,Unsubscribed,2024-08-12
9,12360,Ronald Williams,angelicamelton@example.net,43,Mid Age (36-50 Years Old),Germany,1,mobile,email,10,...,NaN,NaN,NaN,14:23:50,18.56,11.88,3.0,619.23,Unsubscribed,2024-08-12

In [ ]:
behavior_transactions_df.tail(10)

,customer_id,customer_name,email,age,age_group,country,session_id,device,source,event_id,...,discount_pct,amount_usd,payment,last_order_time,cost_usd,margin_usd,total_orders,total_spent,marketing_opt_in,signup_date
760948,19550,Danny Chavez,waterstracy@example.org,65,Senior (51-100 Years Old),United States,119999,mobile,referral,760949,...,NaN,NaN,NaN,15:40:40,7.93,2.98,4.0,406.61,Subscribed,2022-12-08
760949,19550,Danny Chavez,waterstracy@example.org,65,Senior (51-100 Years Old),United States,119999,mobile,referral,760950,...,NaN,NaN,NaN,15:40:40,58.21,29.63,4.0,406.61,Subscribed,2022-12-08
760950,19550,Danny Chavez,waterstracy@example.org,65,Senior (51-100 Years Old),United States,119999,mobile,referral,760951,...,NaN,NaN,NaN,15:40:40,58.21,29.63,4.0,406.61,Subscribed,2022-12-08
760951,19550,Danny Chavez,waterstracy@example.org,65,Senior (51-100 Years Old),United States,119999,mobile,referral,760952,...,NaN,NaN,NaN,15:40:40,24.24,23.83,4.0,406.61,Subscribed,2022-12-08
760952,19550,Danny Chavez,waterstracy@example.org,65,Senior (51-100 Years Old),United States,119999,mobile,referral,760953,...,NaN,NaN,NaN,15:40:40,27.84,23.73,4.0,406.61,Subscribed,2022-12-08
760953,19550,Danny Chavez,waterstracy@example.org,65,Senior (51-100 Years Old),United States,119999,mobile,referral,760954,...,NaN,NaN,NaN,15:40:40,NaN,NaN,4.0,406.61,Subscribed,2022-12-08
760954,19550,Danny Chavez,waterstracy@example.org,65,Senior (51-100 Years Old),United States,119999,mobile,referral,760955,...,15.0,74.66,card,15:40:40,NaN,NaN,4.0,406.61,Subscribed,2022-12-08
760955,453,Antonio Lee,michael73@example.com,61,Senior (51-100 Years Old),India,120000,tablet,direct,760956,...,NaN,NaN,NaN,17:38:54,62.66,56.91,2.0,145.88,Subscribed,2022-09-23
760956,453,Antonio Lee,michael73@example.com,61,Senior (51-100 Years Old),India,120000,tablet,direct,760957,...,NaN,NaN,NaN,17:38:54,14.53,9.80,2.0,145.88,Subscribed,2022-09-23
760957,453,Antonio Lee,michael73@example.com,61,Senior (51-100 Years Old),India,120000,tablet,direct,760958,...,NaN,NaN,NaN,17:38:54,118.29,44.30,2.0,145.88,Subscribed,2022-09-23

**Analyse User Behaviour merge file**

In [ ]:
user_Behaviour = [
    # Customer
    'customer_id', 'age' ,'age_group', 'country',

    # Session
    'session_id', 'device', 'source',

    # Event
    'event_id', 'event_type', 'event_date', 'event_time', 'session_date', 'session_time',

    # Product
    'product_id', 'product_name', 'category',

    # Transaction
    'qty', 'cart_size', 'price_usd', 'discount_pct', 'amount_usd', 'payment', 'last_order_time' ,

    # Metrics
    'total_orders', 'total_spent',

    # Marketing
    'marketing_opt_in'
]

user_Behaviour_df = behavior_transactions_df[user_Behaviour]

In [ ]:
user_Behaviour_df.head()

,customer_id,age,age_group,country,session_id,device,source,event_id,event_type,event_date,...,qty,cart_size,price_usd,discount_pct,amount_usd,payment,last_order_time,total_orders,total_spent,marketing_opt_in
0,12360,43,Mid Age (36-50 Years Old),Germany,1,mobile,email,1,page_view,2021-12-27,...,NaN,NaN,249.08,NaN,NaN,NaN,14:23:50,3.0,619.23,Unsubscribed
1,12360,43,Mid Age (36-50 Years Old),Germany,1,mobile,email,2,page_view,2021-12-27,...,NaN,NaN,6.43,NaN,NaN,NaN,14:23:50,3.0,619.23,Unsubscribed
2,12360,43,Mid Age (36-50 Years Old),Germany,1,mobile,email,3,add_to_cart,2021-12-27,...,1.0,NaN,6.43,NaN,NaN,NaN,14:23:50,3.0,619.23,Unsubscribed
3,12360,43,Mid Age (36-50 Years Old),Germany,1,mobile,email,4,page_view,2021-12-27,...,NaN,NaN,31.71,NaN,NaN,NaN,14:23:50,3.0,619.23,Unsubscribed
4,12360,43,Mid Age (36-50 Years Old),Germany,1,mobile,email,5,page_view,2021-12-27,...,NaN,NaN,11.39,NaN,NaN,NaN,14:23:50,3.0,619.23,Unsubscribed

show the behaviour of customer for example 12360

In [ ]:
cust_id = 12360

cust_df = user_Behaviour_df[user_Behaviour_df['customer_id'] == cust_id]

sessions = cust_df['session_id'].unique()
session_count = cust_df['session_id'].nunique()

print("Customer ID:", cust_id)
print("Total Sessions:", session_count)
print("Session IDs:", sessions)

Customer ID: 12360
Total Sessions: 8
Session IDs: [     1  19187  20072  21681  46216  76865 103818 118949]

In [ ]:
user_Behaviour_df[user_Behaviour_df['session_id'] == 19187]

,customer_id,age,age_group,country,session_id,device,source,event_id,event_type,event_date,...,qty,cart_size,price_usd,discount_pct,amount_usd,payment,last_order_time,total_orders,total_spent,marketing_opt_in
120689,12360,43,Mid Age (36-50 Years Old),Germany,19187,desktop,paid,120690,page_view,2021-05-23,...,NaN,NaN,67.11,NaN,NaN,NaN,14:23:50,3.0,619.23,Unsubscribed
120690,12360,43,Mid Age (36-50 Years Old),Germany,19187,desktop,paid,120691,page_view,2021-05-23,...,NaN,NaN,12.64,NaN,NaN,NaN,14:23:50,3.0,619.23,Unsubscribed
120691,12360,43,Mid Age (36-50 Years Old),Germany,19187,desktop,paid,120692,page_view,2021-05-23,...,NaN,NaN,7.41,NaN,NaN,NaN,14:23:50,3.0,619.23,Unsubscribed
120692,12360,43,Mid Age (36-50 Years Old),Germany,19187,desktop,paid,120693,page_view,2021-05-23,...,NaN,NaN,72.61,NaN,NaN,NaN,14:23:50,3.0,619.23,Unsubscribed
120693,12360,43,Mid Age (36-50 Years Old),Germany,19187,desktop,paid,120694,add_to_cart,2021-05-23,...,1.0,NaN,72.61,NaN,NaN,NaN,14:23:50,3.0,619.23,Unsubscribed
120694,12360,43,Mid Age (36-50 Years Old),Germany,19187,desktop,paid,120695,page_view,2021-05-23,...,NaN,NaN,163.40,NaN,NaN,NaN,14:23:50,3.0,619.23,Unsubscribed
120695,12360,43,Mid Age (36-50 Years Old),Germany,19187,desktop,paid,120696,page_view,2021-05-23,...,NaN,NaN,185.93,NaN,NaN,NaN,14:23:50,3.0,619.23,Unsubscribed
120696,12360,43,Mid Age (36-50 Years Old),Germany,19187,desktop,paid,120697,checkout,2021-05-23,...,NaN,1.0,NaN,NaN,NaN,NaN,14:23:50,3.0,619.23,Unsubscribed
120697,12360,43,Mid Age (36-50 Years Old),Germany,19187,desktop,paid,120698,purchase,2021-05-23,...,NaN,NaN,NaN,20.0,58.09,card,14:23:50,3.0,619.23,Unsubscribed

*From the example of analysis above a customer can have multiple sessions, and each session consists of multiple events. Each event represents an action taken by the customer, such as page view, add to cart, checkout or purchase. However, not every session completes all steps of the customer journey.*

In [ ]:
# Understand User Activity (Basic EDA)
# Track user journey
user_Behaviour_df['event_type'].value_counts()

event_type
page_view      539343
add_to_cart    143126
checkout        44909
purchase        33580
Name: count, dtype: int64

In [ ]:
event_counts = user_Behaviour_df['event_type'].value_counts()

total = event_counts['page_view']

add_to_cart_rate = event_counts['add_to_cart'] / total
checkout_rate = event_counts['checkout'] / total
purchase_rate = event_counts['purchase'] / total

print (f"Total Page View:  {total}")
print(f"Add to Cart Rate: {add_to_cart_rate:.2%}")
print(f"Checkout Rate: {checkout_rate:.2%}")
print(f"Purchase Rate: {purchase_rate:.2%}")

Total Page View:  539343
Add to Cart Rate: 26.54%
Checkout Rate: 8.33%
Purchase Rate: 6.23%

* Most user activities are page views (393k), but only a small portion convert into purchases (24k)
- While 26.54% of users add items to cart, only 6.23% complete a purchase, indicating a significant drop-off throughout the conversion funnel.*

In [ ]:
# Engagement Analysis
# Events per session
user_Behaviour_df.groupby('session_id')['event_type'].count()

session_id
1         10
2          8
3          5
4          2
5          6
          ..
119996     8
119997     8
119998     3
119999     7
120000     3
Name: event_type, Length: 120000, dtype: int64

In [ ]:
user_Behaviour_df.groupby('session_id')['event_type'].count().mean()

np.float64(6.341316666666667)

*On average, users perform around 6 actions per session, suggesting moderate engagement. This indicates that users interact multiple times within a session before leaving or completing a purchase.*

In [ ]:
#Sessions per customer
user_Behaviour_df.groupby('customer_id')['session_id'].nunique()

customer_id
1        5
2        3
3        5
4        9
5        9
        ..
19996    2
19997    4
19998    9
19999    7
20000    2
Name: session_id, Length: 19945, dtype: int64

In [ ]:
user_Behaviour_df.groupby('customer_id')['session_id'].nunique().mean()

np.float64(6.0165455001253445)

*Most customers have multiple sessions, suggesting repeat engagement and continued interaction with the platform over time.*

In [ ]:
user_Behaviour_df.groupby('session_id')['event_type'].count().describe()

count    120000.000000
mean          6.341317
std           3.424481
min           1.000000
25%           3.000000
50%           6.000000
75%           9.000000
max          17.000000
Name: event_type, dtype: float64

In [ ]:
#Conversion Rate
purchase_sessions = user_Behaviour_df[user_Behaviour_df['event_type']=='purchase']['session_id'].nunique()
total_sessions = user_Behaviour_df['session_id'].nunique()

conversion_rate = purchase_sessions / total_sessions
print(f"Conversion Rate: {conversion_rate:.2%}")

Conversion Rate: 27.98%

*Only a small percentage of sessions result in purchases, indicating low conversion efficiency.*

In [ ]:
# Device analysis
device_revenue = user_Behaviour_df.groupby('device')['amount_usd'].sum()
device_revenue

device
desktop    1683869.59
mobile     2496380.33
tablet      312967.55
Name: amount_usd, dtype: float64

*Most revenue is generated from [device], indicating that this platform plays a key role in driving sales*

In [ ]:
# Marketing Impact
marketing_impact = user_Behaviour_df.groupby('marketing_opt_in')['amount_usd'].mean()
marketing_impact

marketing_opt_in
Subscribed      133.910870
Unsubscribed    133.675615
Name: amount_usd, dtype: float64

*The average spending between subscribed and unsubscribed customers is nearly the same, indicating that marketing opt-in does not significantly impact spending behavior.*

In [ ]:
# Customer Segmentation (Age)
age_spending = user_Behaviour_df.groupby('age_group')['amount_usd'].sum()
age_spending

/tmp/ipykernel_4359/2839587512.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  age_spending = user_Behaviour_df.groupby('age_group')['amount_usd'].sum()

age_group
Teen (0–18 Years Old)              75636.67
Young Adult (19-25 Years Old)     538265.60
Adult (26-35 Years Old)           778113.67
Mid Age (36-50 Years Old)        1165417.47
Senior (51-100 Years Old)        1935784.06
Name: amount_usd, dtype: float64

*Senior customers contribute the highest total spending, followed by mid-age and adult groups, indicating that older customers are the primary revenue drivers.*

In [ ]:
# a filtered dataset with only customer that end with purchase item
purchase_sessions = user_Behaviour_df[
    user_Behaviour_df['event_type'] == 'purchase']['session_id'].unique()

In [ ]:
purchase_user_df = user_Behaviour_df[
    user_Behaviour_df['session_id'].isin(purchase_sessions)
]

In [ ]:
purchase_user_df.head()

,customer_id,age,age_group,country,session_id,device,source,event_id,event_type,event_date,...,qty,cart_size,price_usd,discount_pct,amount_usd,payment,last_order_time,total_orders,total_spent,marketing_opt_in
10,13917,68,Senior (51-100 Years Old),Poland,2,desktop,organic,11,page_view,2025-01-31,...,NaN,NaN,15.33,NaN,NaN,NaN,23:07:42,1.0,85.72,Subscribed
11,13917,68,Senior (51-100 Years Old),Poland,2,desktop,organic,12,page_view,2025-01-31,...,NaN,NaN,107.15,NaN,NaN,NaN,23:07:42,1.0,85.72,Subscribed
12,13917,68,Senior (51-100 Years Old),Poland,2,desktop,organic,13,add_to_cart,2025-01-31,...,1.0,NaN,107.15,NaN,NaN,NaN,23:07:42,1.0,85.72,Subscribed
13,13917,68,Senior (51-100 Years Old),Poland,2,desktop,organic,14,page_view,2025-01-31,...,NaN,NaN,10.21,NaN,NaN,NaN,23:07:42,1.0,85.72,Subscribed
14,13917,68,Senior (51-100 Years Old),Poland,2,desktop,organic,15,page_view,2025-01-31,...,NaN,NaN,9.27,NaN,NaN,NaN,23:07:42,1.0,85.72,Subscribed

In [ ]:
purchase_user_df.tail()

,customer_id,age,age_group,country,session_id,device,source,event_id,event_type,event_date,...,qty,cart_size,price_usd,discount_pct,amount_usd,payment,last_order_time,total_orders,total_spent,marketing_opt_in
760950,19550,65,Senior (51-100 Years Old),United States,119999,mobile,referral,760951,add_to_cart,2025-04-22,...,1.0,NaN,87.84,NaN,NaN,NaN,15:40:40,4.0,406.61,Subscribed
760951,19550,65,Senior (51-100 Years Old),United States,119999,mobile,referral,760952,page_view,2025-04-22,...,NaN,NaN,48.07,NaN,NaN,NaN,15:40:40,4.0,406.61,Subscribed
760952,19550,65,Senior (51-100 Years Old),United States,119999,mobile,referral,760953,page_view,2025-04-22,...,NaN,NaN,51.57,NaN,NaN,NaN,15:40:40,4.0,406.61,Subscribed
760953,19550,65,Senior (51-100 Years Old),United States,119999,mobile,referral,760954,checkout,2025-04-22,...,NaN,1.0,NaN,NaN,NaN,NaN,15:40:40,4.0,406.61,Subscribed
760954,19550,65,Senior (51-100 Years Old),United States,119999,mobile,referral,760955,purchase,2025-04-22,...,NaN,NaN,NaN,15.0,74.66,card,15:40:40,4.0,406.61,Subscribed

**Validate purchase_df**

In [ ]:
#Check purchase_df
purchase_user_df['customer_id'].unique()[:5]

array([13917,  1022,  6145,  3152, 12378])

In [ ]:
purchase_user_df[
    purchase_user_df['customer_id'] == 6145][['customer_id', 'session_id']].drop_duplicates()

       customer_id  session_id
38            6145          10
94468         6145       15028

In [ ]:
purchase_user_df[
    purchase_user_df['session_id'] == 15028
][[
    'customer_id', 'session_id', 'event_type',
    'event_time', 'event_date', 'product_name', 'amount_usd'
]].sort_values('event_time')

,customer_id,session_id,event_type,event_time,event_date,product_name,amount_usd
94468,6145,15028,page_view,06:35:19,2021-03-25,Conditioner Olive 378,NaN
94469,6145,15028,add_to_cart,06:35:43,2021-03-25,Conditioner Olive 378,NaN
94470,6145,15028,checkout,06:54:19,2021-03-25,NaN,NaN
94471,6145,15028,purchase,07:03:19,2021-03-25,NaN,205.72

In [ ]:
purchase_user_df[
    purchase_user_df['session_id'] == 10
][[
    'customer_id', 'session_id', 'event_type',
    'event_time', 'event_date', 'product_name', 'amount_usd'
]].sort_values('event_time')

,customer_id,session_id,event_type,event_time,event_date,product_name,amount_usd
38,6145,10,page_view,19:11:13,2024-12-04,Shampoo LawnGreen 601,NaN
39,6145,10,add_to_cart,19:11:44,2024-12-04,Shampoo LawnGreen 601,NaN
40,6145,10,page_view,19:29:13,2024-12-04,E-book Blue 458,NaN
41,6145,10,page_view,19:41:13,2024-12-04,Sunscreen Orange 916,NaN
42,6145,10,page_view,19:56:13,2024-12-04,Moisturizer RosyBrown 568,NaN
43,6145,10,page_view,20:03:13,2024-12-04,SSD Orchid 272,NaN
44,6145,10,add_to_cart,20:04:03,2024-12-04,SSD Orchid 272,NaN
45,6145,10,checkout,20:16:13,2024-12-04,NaN,NaN
46,6145,10,purchase,20:24:13,2024-12-04,NaN,137.35

In [ ]:
purchase_user_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 300230 entries, 10 to 760954
Data columns (total 26 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   customer_id       300230 non-null  int64
 1   age               300230 non-null  int64
 2   age_group         300230 non-null  category
 3   country           300230 non-null  object
 4   session_id        300230 non-null  int64
 5   device            300230 non-null  object
 6   source            300230 non-null  object
 7   event_id          300230 non-null  int64
 8   event_type        300230 non-null  object
 9   event_date        300230 non-null  object
 10  event_time        300230 non-null  object
 11  session_date      300230 non-null  object
 12  session_time      300230 non-null  object
 13  product_id        233070 non-null  float64
 14  product_name      233070 non-null  object
 15  category          233070 non-null  object
 16  qty               59163 non-null   float64
 17  cart_size         33580 non-null   float64
 18  price_usd         233070 non-null  float64
 19  discount_pct      33580 non-null   float64
 20  amount_usd        33580 non-null   float64
 21  payment           33580 non-null   object
 22  last_order_time   300230 non-null  object
 23  total_orders      300230 non-null  float64
 24  total_spent       300230 non-null  float64
 25  marketing_opt_in  300230 non-null  object
dtypes: category(1), float64(8), int64(4), object(13)
memory usage: 59.8+ MB

In [ ]:
purchase_user_df.columns.values

array(['customer_id', 'age', 'age_group', 'country', 'session_id',
       'device', 'source', 'event_id', 'event_type', 'event_date',
       'event_time', 'session_date', 'session_time', 'product_id',
       'product_name', 'category', 'qty', 'cart_size', 'price_usd',
       'discount_pct', 'amount_usd', 'payment', 'last_order_time',
       'total_orders', 'total_spent', 'marketing_opt_in'], dtype=object)

In [ ]:
# Total sessions (original)
total_sessions = user_Behaviour_df['session_id'].nunique()

# Purchase sessions
purchase_sessions_count = purchase_user_df['session_id'].nunique()

#conversion Rate
conversion_rate = purchase_sessions_count / total_sessions

print(f"Total Sessions        : {total_sessions}")
print(f"Purchase Sessions     : {purchase_sessions_count}")
print(f"Conversion Rate       : {conversion_rate:.2%}")

Total Sessions        : 120000
Purchase Sessions     : 33580
Conversion Rate       : 27.98%

In [ ]:
# customer vs purchase customer
# Total customers
total_customer = user_Behaviour_df['customer_id'].nunique()

# Total Purchase customers
purchase_customer_count = purchase_user_df['customer_id'].nunique()

#customer conversion rate
customerconversion_rate = purchase_customer_count / total_customer

print(f"Total Customer: {total_customer}")
print(f"Purchase Customer: {purchase_customer_count}")
print(f"Customer conversion Rate: {customerconversion_rate:.2%}")

Total Customer: 19945
Purchase Customer: 16268
Customer conversion Rate: 81.56%

*Out of approximately 19,000 customers, 81.56% have made a purchase. However, only 27.98% of sessions lead to conversion, indicating that customers often require multiple sessions before completing a purchase.*

In [ ]:
user_Behaviour_df['event_type'].value_counts()

event_type
page_view      539343
add_to_cart    143126
checkout        44909
purchase        33580
Name: count, dtype: int64

In [ ]:
purchase_user_df['category'].value_counts()

category
Books             44640
Toys              41034
Beauty            38072
Fashion           31517
Home & Kitchen    30227
Sports            28095
Electronics       19485
Name: count, dtype: int64

# Predict Cart Abandonment

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score
from sklearn.ensemble import RandomForestClassifier

In [ ]:
customers = pd.read_csv("/content/customers.csv")
sessions = pd.read_csv("/content/session.csv")
events = pd.read_csv("/content/events.csv")

In [ ]:
# Inspect dataset structure, data types, and sample rows
print("CUSTOMERS")
print(customers.head())
print(customers.info())
print()

print("SESSIONS")
print(sessions.head())
print(sessions.info())
print()

print("EVENTS")
print(events.head())
print(events.info())

CUSTOMERS
   customer_id              name                       email country  age  \
0            1  Jennifer Salinas      nicholas59@example.org      JP   71
1            2     Phillip Ramos  christinarubio@example.com      IN   26
2            3       Dawn Fowler       jessica03@example.org      BR   21
3            4      Mario Butler         paula27@example.org      FR   63
4            5       Amber Brown         kevin85@example.net      BR   19

  signup_date  marketing_opt_in
0  2020-09-04              True
1  2020-04-05             False
2  2023-08-31              True
3  2022-06-30              True
4  2022-07-22              True
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       20000 non-null  int64
 1   name              20000 non-null  object
 2   email             20000 non-null  object
 3   country           20000 non-null  object
 4   age               20000 non-null  int64
 5   signup_date       20000 non-null  object
 6   marketing_opt_in  20000 non-null  bool
dtypes: bool(1), int64(2), object(4)
memory usage: 957.2+ KB
None

SESSIONS
   session_id  customer_id           start_time   device   source country
0           1        12360  2021-12-27T00:01:36   mobile    email      DE
1           2        13917  2025-01-31T21:29:42  desktop  organic      PL
2           3         1022  2024-02-19T00:52:50   tablet  organic      FR
3           4         2882  2024-08-04T19:54:31   mobile   direct      GB
4           5         1286  2022-06-28T13:58:08  desktop    email      ES
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 6 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   session_id   120000 non-null  int64
 1   customer_id  120000 non-null  int64
 2   start_time   120000 non-null  object
 3   device       120000 non-null  object
 4   source       120000 non-null  object
 5   country      120000 non-null  object
dtypes: int64(2), object(4)
memory usage: 5.5+ MB
None

EVENTS
   event_id  session_id            timestamp   event_type  product_id  qty  \
0         1           1  2021-12-27T00:08:36    page_view        93.0  NaN
1         2           1  2021-12-27T00:16:36    page_view      1005.0  NaN
2         3           1  2021-12-27T00:18:01  add_to_cart      1005.0  1.0
3         4           1  2021-12-27T00:45:36    page_view       918.0  NaN
4         5           1  2021-12-27T01:03:36    page_view       946.0  NaN

   cart_size payment  discount_pct  amount_usd
0        NaN     NaN           NaN         NaN
1        NaN     NaN           NaN         NaN
2        NaN     NaN           NaN         NaN
3        NaN     NaN           NaN         NaN
4        NaN     NaN           NaN         NaN
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 760958 entries, 0 to 760957
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   event_id      760958 non-null  int64
 1   session_id    760958 non-null  int64
 2   timestamp     760958 non-null  object
 3   event_type    760958 non-null  object
 4   product_id    682469 non-null  float64
 5   qty           143126 non-null  float64
 6   cart_size     44909 non-null   float64
 7   payment       33580 non-null   object
 8   discount_pct  33580 non-null   float64
 9   amount_usd    33580 non-null   float64
dtypes: float64(5), int64(2), object(3)
memory usage: 58.1+ MB
None

In [ ]:
print("Missing values in customers:")
print(customers.isnull().sum())
print()

print("Missing values in sessions:")
print(sessions.isnull().sum())
print()

print("Missing values in events:")
print(events.isnull().sum())

Missing values in customers:
customer_id         0
name                0
email               0
country             0
age                 0
signup_date         0
marketing_opt_in    0
dtype: int64

Missing values in sessions:
session_id     0
customer_id    0
start_time     0
device         0
source         0
country        0
dtype: int64

Missing values in events:
event_id             0
session_id           0
timestamp            0
event_type           0
product_id       78489
qty             617832
cart_size       716049
payment         727378
discount_pct    727378
amount_usd      727378
dtype: int64

In [ ]:
# Convert date/time columns into datetime format
# This is necessary for time-based feature engineering such as session duration and account age
customers["signup_date"] = pd.to_datetime(customers["signup_date"], errors="coerce")
sessions["start_time"] = pd.to_datetime(sessions["start_time"], errors="coerce")
events["timestamp"] = pd.to_datetime(events["timestamp"], errors="coerce")

Datetime conversion enables time-based analysis and feature engineering. For example, we later compute session duration and how long a customer has been registered before the session occurred.

In [ ]:
# Convert date/time columns into datetime format
# This is necessary for time-based feature engineering such as session duration and account age
customers = customers.drop_duplicates()
sessions = sessions.drop_duplicates()
events = events.drop_duplicates()

In [ ]:
events["event_type"] = events["event_type"].astype(str).str.strip().str.lower()

Standardizing event labels ensures that all events of the same type are grouped correctly during aggregation, avoiding duplication caused by inconsistent formatting such as capitalization and extra spaces.

In [ ]:
event_counts = events.pivot_table(
    index="session_id",
    columns="event_type",
    values="event_id",
    aggfunc="count",
    fill_value=0
).reset_index()

This step transforms event-level logs into session-level behavioral features. It allows us to quantify how much browsing, cart activity, and purchasing happened in each session.

In [ ]:
print(event_counts.head())
print(event_counts.columns.tolist())

event_type  session_id  add_to_cart  checkout  page_view  purchase
0                    1            3         0          7         0
1                    2            1         1          5         1
2                    3            1         1          2         1
3                    4            0         0          2         0
4                    5            0         0          6         0
['session_id', 'add_to_cart', 'checkout', 'page_view', 'purchase']

In [ ]:
#just to make sure key event column exists
for col in ["page_view", "add_to_cart", "purchase"]:
    if col not in event_counts.columns:
        event_counts[col] = 0

In [ ]:
# These summarize how active and engaged each session was
session_agg = events.groupby("session_id").agg(
    num_events=("event_id", "count"),
    num_unique_products=("product_id", "nunique"),
    total_qty_added=("qty", "sum"),
    max_cart_size=("cart_size", "max"),
    avg_discount_pct=("discount_pct", "mean"),
    total_amount_usd=("amount_usd", "sum"),
    first_event_time=("timestamp", "min"),
    last_event_time=("timestamp", "max")
).reset_index()

This block generates higher-level behavioral features for each session. These features help the model distinguish between light browsing, engaged shopping, and sessions that are closer to conversion.

In [ ]:
# Fill missing aggregated numeric fields with 0
#cleaning the Nan to 0
numeric_cols = ["num_unique_products", "total_qty_added", "max_cart_size", "avg_discount_pct", "total_amount_usd"]
session_agg[numeric_cols] = session_agg[numeric_cols].fillna(0)

In [ ]:
session_agg["session_duration_min"] = (
    (session_agg["last_event_time"] - session_agg["first_event_time"]).dt.total_seconds() / 60
)

session_agg["session_duration_min"] = session_agg["session_duration_min"].fillna(0)

add new column to the table

Session duration was computed as the time difference between the first and last event within each session. This feature captures user engagement level, as longer sessions may indicate higher interest or decision-making activity.

In [ ]:
# Merge and Combine event counts and aggregated behavioral metrics into one session-level feature table
session_features = event_counts.merge(session_agg, on="session_id", how="left")
print(session_features.head())

   session_id  add_to_cart  checkout  page_view  purchase  num_events  \
0           1            3         0          7         0          10
1           2            1         1          5         1           8
2           3            1         1          2         1           5
3           4            0         0          2         0           2
4           5            0         0          6         0           6

   num_unique_products  total_qty_added  max_cart_size  avg_discount_pct  \
0                    7              3.0            0.0               0.0
1                    5              1.0            1.0              20.0
2                    2              1.0            1.0               0.0
3                    2              0.0            0.0               0.0
4                    6              0.0            0.0               0.0

   total_amount_usd    first_event_time     last_event_time  \
0              0.00 2021-12-27 00:08:36 2021-12-27 01:59:36
1             85.72 2025-01-31 21:48:42 2025-01-31 23:07:42
2            116.17 2024-02-19 00:57:50 2024-02-19 01:17:50
3              0.00 2024-08-04 20:24:31 2024-08-04 20:47:31
4              0.00 2022-06-28 14:19:08 2022-06-28 15:27:08

   session_duration_min
0                 111.0
1                  79.0
2                  20.0
3                  23.0
4                  68.0

In [ ]:
# Keep only sessions where at least one item was added to cart
# These are the sessions relevant for cart abandonment analysis
cart_sessions = session_features[session_features["add_to_cart"] > 0].copy()

# Define cart abandonment label using business logic
# abandoned = 1 if the session had add-to-cart activity but no purchase
# abandoned = 0 if the session had add-to-cart activity and completed a purchase
cart_sessions["abandoned"] = np.where(
    cart_sessions["purchase"] > 0,
    0,
    1
)

print(cart_sessions[["session_id", "add_to_cart", "purchase", "abandoned"]].head())
print(cart_sessions["abandoned"].value_counts())

   session_id  add_to_cart  purchase  abandoned
0           1            3         0          1
1           2            1         1          0
2           3            1         1          0
7           8            1         0          1
8           9            1         0          1
abandoned
1    47938
0    33580
Name: count, dtype: int64

This is a form of target engineering where cart abandonment is defined using business logic. A session is labeled as abandoned if items were added to the cart but no purchase was completed.

In [ ]:
# Merge behavioral session features with session metadata and customer profile data
# This enriches the model with device, source, country, age, and signup history
df = cart_sessions.merge(sessions, on="session_id", how="left")
df = df.merge(customers, on="customer_id", how="left")

print(df.head())
print(df.columns.tolist())

   session_id  add_to_cart  checkout  page_view  purchase  num_events  \
0           1            3         0          7         0          10
1           2            1         1          5         1           8
2           3            1         1          2         1           5
3           8            1         1          1         0           3
4           9            1         0          1         0           2

   num_unique_products  total_qty_added  max_cart_size  avg_discount_pct  ...  \
0                    7              3.0            0.0               0.0  ...
1                    5              1.0            1.0              20.0  ...
2                    2              1.0            1.0               0.0  ...
3                    1              1.0            1.0               0.0  ...
4                    1              1.0            0.0               0.0  ...

           start_time   device   source  country_x                  name  \
0 2021-12-27 00:01:36   mobile    email         DE       Ronald Williams
1 2025-01-31 21:29:42  desktop  organic         PL            Brian Chen
2 2024-02-19 00:52:50   tablet  organic         FR        Kristen Hughes
3 2020-07-10 10:35:54   mobile    email         DE  Stephanie Stevens MD
4 2024-02-22 16:57:44   mobile   direct         PL         Manuel Bailey

                        email country_y age signup_date marketing_opt_in
0  angelicamelton@example.net        DE  43  2024-08-12            False
1    mathiscarrie@example.org        PL  68  2025-07-09             True
2       bradley26@example.net        FR  45  2023-03-31            False
3     ahutchinson@example.com        DE  56  2020-07-06            False
4         vthomas@example.net        PL  63  2023-01-16             True

[5 rows x 26 columns]
['session_id', 'add_to_cart', 'checkout', 'page_view', 'purchase', 'num_events', 'num_unique_products', 'total_qty_added', 'max_cart_size', 'avg_discount_pct', 'total_amount_usd', 'first_event_time', 'last_event_time', 'session_duration_min', 'abandoned', 'customer_id', 'start_time', 'device', 'source', 'country_x', 'name', 'email', 'country_y', 'age', 'signup_date', 'marketing_opt_in']

Adds more information to each session:

from sessions: device, source, country, start time
from customers: age, signup date, marketing_opt_in

This merging step creates a unified modeling dataset where behavioral session features are combined with session-level metadata and customer profile attributes, enabling richer context for predicting cart abandonment.

In [ ]:
# Create account-age feature
# Measures how many days passed between signup and the current session
df["days_since_signup"] = (df["start_time"] - df["signup_date"]).dt.days

In [ ]:
# Extract session time features
# These can capture behavioral differences by hour of day or day of week
df["session_hour"] = df["start_time"].dt.hour
df["session_dayofweek"] = df["start_time"].dt.dayofweek

In [ ]:
# Convert marketing_opt_in into numeric format for modeling
df["marketing_opt_in"] = df["marketing_opt_in"].astype(str).str.lower().map({
    "true": 1,
    "false": 0
})

Creates extra features:

- days_since_signup
- session_hour
- session_dayofweek
- umeric marketing flag

These features can help the model detect patterns like:

- newer users abandon more
- mobile/email traffic behaves differently at certain hours
- engagement may vary by weekday/weekend

In [ ]:
feature_cols = [
    "page_view",
    "num_events",
    "num_unique_products",
    "session_duration_min",
    "device",
    "source",
    "country_x",   # from sessions
    "age",
    "days_since_signup",
    "marketing_opt_in",
    "session_hour",
    "session_dayofweek"
]

In [ ]:
print(df.columns.tolist())

['session_id', 'add_to_cart', 'checkout', 'page_view', 'purchase', 'num_events', 'num_unique_products', 'total_qty_added', 'max_cart_size', 'avg_discount_pct', 'total_amount_usd', 'first_event_time', 'last_event_time', 'session_duration_min', 'abandoned', 'customer_id', 'start_time', 'device', 'source', 'country_x', 'name', 'email', 'country_y', 'age', 'signup_date', 'marketing_opt_in', 'days_since_signup', 'session_hour', 'session_dayofweek']

In [ ]:
df = df.rename(columns={
    "country_x": "session_country",
    "country_y": "customer_country"
})

In [ ]:
# Select only pre-purchase behavioral and contextual features
# Excluding leakage-prone late-stage cart variables
feature_cols = [
    "page_view",
    "num_events",
    "num_unique_products",
    "session_duration_min",
    "device",
    "source",
    "session_country",
    "age",
    "days_since_signup",
    "marketing_opt_in",
    "session_hour",
    "session_dayofweek"
]

In [ ]:
target_col = "abandoned"

The final feature selection excludes leakage-prone variables and focuses on pre-purchase behavioral and contextual features. This improves the model’s realism and ensures better generalization to real-world cart abandonment prediction scenarios.

In [ ]:
# Separate input features (X) from the prediction target (y)
X = df[feature_cols].copy()
y = df[target_col].copy()

- X = what the model uses to learn
- y = what the model tries to predict

In [ ]:
print(X.head())
print(y.value_counts())

   page_view  num_events  num_unique_products  session_duration_min   device  \
0          7          10                    7            111.000000   mobile
1          5           8                    5             79.000000  desktop
2          2           5                    2             20.000000   tablet
3          1           3                    1             18.000000   mobile
4          1           2                    1              1.166667   mobile

    source session_country  age  days_since_signup  marketing_opt_in  \
0    email              DE   43               -959                 0
1  organic              PL   68               -159                 1
2  organic              FR   45                325                 0
3    email              DE   56                  4                 0
4   direct              PL   63                402                 1

   session_hour  session_dayofweek
0             0                  0
1            21                  4
2             0                  0
3            10                  4
4            16                  3
abandoned
1    47938
0    33580
Name: count, dtype: int64

In [ ]:
# Define numeric and categorical feature groups for preprocessing
numeric_features = [
    "page_view",
    "num_events",
    "num_unique_products",
    "session_duration_min",
    "age",
    "days_since_signup",
    "marketing_opt_in",
    "session_hour",
    "session_dayofweek"
]

categorical_features = [
    "device",
    "source",
    "session_country"
]

Numeric and categorical features were separated to ensure appropriate preprocessing. Numerical variables are directly usable by models, while categorical variables require encoding before being used in machine learning algorithms.

In [ ]:
numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median"))
])

categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer(transformers=[
    ("num", numeric_transformer, numeric_features),
    ("cat", categorical_transformer, categorical_features)
])

Prepares data for modeling:

- numeric nulls → filled with median
- categorical nulls → filled with most frequent value
- categories → converted into machine-readable columns using one-hot encoding

This preprocessing pipeline handles missing values and encodes categorical variables into numerical format using imputation and one-hot encoding, ensuring the dataset is fully compatible with machine learning models.

In [ ]:
# Split data into training and testing sets
# 80% is used for learning, 20% is reserved for evaluating generalization
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

This split prevents evaluation on the same data used for training, which helps measure how well the model performs on unseen sessions.

In [ ]:
model = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("classifier", RandomForestClassifier(
        n_estimators=200,
        random_state=42,
        class_weight="balanced"
    ))
])

Builds a pipeline with:

- preprocessing
- classifier

Preprocessing dulu
- fill missing values
- encode categorical
- prepare numeric data

A Random Forest classification pipeline was built by combining preprocessing steps with a supervised learning model. Random Forest was chosen as a strong baseline due to its ability to handle mixed feature types and capture complex non-linear relationships in structured tabular data.

In [ ]:
# Train the model on historical session data
# The model learns patterns associated with abandoned vs completed cart sessions
model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  ['page_view', 'num_events',
                                                   'num_unique_products',
                                                   'session_duration_min',
                                                   'age', 'days_since_signup',
                                                   'marketing_opt_in',
                                                   'session_hour',
                                                   'session_dayofweek']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['device', 'source',
                                                   'session_country'])])),
                ('classifier',
                 RandomForestClassifier(class_weight='balanced',
                                        n_estimators=200, random_state=42))])

During training, the model learns statistical patterns from historical sessions, such as whether shorter sessions, certain traffic sources, or certain device types are associated with higher abandonment risk.

In [ ]:
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]

print("Classification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("ROC-AUC Score:")
print(roc_auc_score(y_test, y_prob))

Classification Report:
              precision    recall  f1-score   support

           0       0.79      0.88      0.83      6716
           1       0.91      0.84      0.87      9588

    accuracy                           0.86     16304
   macro avg       0.85      0.86      0.85     16304
weighted avg       0.86      0.86      0.86     16304

Confusion Matrix:
[[5933  783]
 [1578 8010]]
ROC-AUC Score:
0.9345186980549193

The model achieved strong predictive performance on unseen test data, suggesting that behavioral and contextual features provide useful signals for identifying cart abandonment risk.

In [ ]:
feature_preview = df[[
    "session_id", "customer_id", "page_view", "add_to_cart",
    "num_events", "session_duration_min", "device", "source", "abandoned"
]].head(10)

print(feature_preview)

   session_id  customer_id  page_view  add_to_cart  num_events  \
0           1        12360          7            3          10
1           2        13917          5            1           8
2           3         1022          2            1           5
3           8         5687          1            1           3
4           9         6476          1            1           2
5          10         6145          5            2           9
6          14        13206          7            2           9
7          15         3152          5            1           8
8          16         2405          8            2          10
9          17        16912          3            2           5

   session_duration_min   device   source  abandoned
0            111.000000   mobile    email          1
1             79.000000  desktop  organic          0
2             20.000000   tablet  organic          0
3             18.000000   mobile    email          1
4              1.166667   mobile   direct          1
5             73.000000   mobile  organic          0
6             96.000000   tablet   direct          1
7             64.000000   mobile    email          0
8            108.500000   tablet  organic          1
9             22.000000   mobile    email          1

The preview confirms the final structure of the modeling dataset, where each row corresponds to a customer session and includes both behavioral features and the abandonment outcome.

In [ ]:
import joblib

joblib.dump(model, "cart_abandonment_model.pkl")

['cart_abandonment_model.pkl']

# Recommend Next Best Products

In [ ]:
purchase_history = (
    orderItems_df
    .merge(orders_df[["order_id", "customer_id", "order_time"]], on="order_id", how="left")
    .merge(products_df, on="product_id", how="left")
)

In [ ]:
purchase_history.head()

,order_id,product_id,unit_price_usd,quantity,line_total_usd,customer_id,order_time,category,name,price_usd,cost_usd,margin_usd
0,1,226,107.15,1,107.15,13917,23:07:42,Home & Kitchen,Toaster MediumSlateBlue 575,107.15,65.65,41.50
1,2,771,116.17,1,116.17,1022,01:17:50,Fashion,Socks Orange 300,116.17,70.22,45.95
2,3,415,94.49,1,94.49,6145,20:24:13,Beauty,Shampoo LawnGreen 601,94.49,58.26,36.23
3,3,24,42.86,1,42.86,6145,20:24:13,Electronics,SSD Orchid 272,42.86,27.37,15.49
4,4,1157,32.18,1,32.18,3152,08:50:47,Toys,Board Game DarkSeaGreen 297,32.18,22.43,9.75

In [ ]:
# based on customer review
recommendation_df = purchase_history.merge(
    reviews_df[["order_id", "product_id", "rating"]],
    on=["order_id", "product_id"],
    how="left"
)

In [ ]:
recommendation_df

,order_id,product_id,unit_price_usd,quantity,line_total_usd,customer_id,order_time,category,name,price_usd,cost_usd,margin_usd,rating
0,1,226,107.15,1,107.15,13917,23:07:42,Home & Kitchen,Toaster MediumSlateBlue 575,107.15,65.65,41.50,NaN
1,2,771,116.17,1,116.17,1022,01:17:50,Fashion,Socks Orange 300,116.17,70.22,45.95,NaN
2,3,415,94.49,1,94.49,6145,20:24:13,Beauty,Shampoo LawnGreen 601,94.49,58.26,36.23,NaN
3,3,24,42.86,1,42.86,6145,20:24:13,Electronics,SSD Orchid 272,42.86,27.37,15.49,NaN
4,4,1157,32.18,1,32.18,3152,08:50:47,Toys,Board Game DarkSeaGreen 297,32.18,22.43,9.75,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
59104,33578,1151,9.27,1,9.27,15731,07:34:01,Toys,Puzzle OldLace 463,9.27,5.12,4.15,NaN
59105,33578,1095,77.20,1,77.20,15731,07:34:01,Toys,Action Figure BlueViolet 416,77.20,42.93,34.27,NaN
59106,33578,815,131.78,1,131.78,15731,07:34:01,Fashion,Socks GoldenRod 963,131.78,89.61,42.17,NaN
59107,33579,981,22.22,1,22.22,15971,16:11:57,Books,Hardcover Blue 431,22.22,14.88,7.34,NaN
59108,33580,606,87.84,1,87.84,19550,10:45:56,Sports,Water Bottle DarkSeaGreen 136,87.84,58.21,29.63,NaN

In [ ]:
print(behavior_df["event_type"].unique())

['page_view' 'add_to_cart' 'checkout' 'purchase']

In [ ]:
print(behavior_df[behavior_df["event_type"] == "purchase"][["product_id", "name_y", "category"]].head(10))
print("\nNon-null count:")
print(behavior_df[behavior_df["event_type"] == "purchase"][["product_id", "name_y", "category"]].notna().sum())

     product_id name_y category
17          NaN    NaN      NaN
22          NaN    NaN      NaN
46          NaN    NaN      NaN
71          NaN    NaN      NaN
93          NaN    NaN      NaN
156         NaN    NaN      NaN
170         NaN    NaN      NaN
191         NaN    NaN      NaN
214         NaN    NaN      NaN
247         NaN    NaN      NaN

Non-null count:
product_id    0
name_y        0
category      0
dtype: int64

# Product Recommender

In [ ]:
# ── Module 3: Product Recommender (fixed) ──
from itertools import combinations
from collections import defaultdict

Filter the right events

In [ ]:
# Use add_to_cart events since purchase rows have no product info
purchases = behavior_df[behavior_df["event_type"] == "add_to_cart"][
    ["customer_id", "product_id", "name_y", "category"]
].dropna()

print(f"Working with {len(purchases)} add-to-cart events")
print(f"Unique products: {purchases['product_id'].nunique()}")
print(f"Unique customers: {purchases['customer_id'].nunique()}")

Working with 143126 add-to-cart events
Unique products: 1197
Unique customers: 19660

Build the co-cart matrix

In [ ]:
# Rebuild co-cart matrix with clean IDs
co_purchases = defaultdict(int)

for customer, group in purchases.groupby("customer_id"):
    products = group["product_id"].tolist()
    if len(products) < 2:
        continue
    for p1, p2 in combinations(set(products), 2):
        co_purchases[(p1, p2)] += 1
        co_purchases[(p2, p1)] += 1

print(f"\nTotal product pairs found: {len(co_purchases)}")

Total product pairs found: 667524

In [ ]:
# ── Product lookup table (id → name & category) ──
product_lookup = (
    purchases[["product_id", "name_y", "category"]]
    .drop_duplicates("product_id")
    .set_index("product_id")
)
# Fix product_id display (remove decimal)
purchases["product_id"] = purchases["product_id"].astype(int)
product_lookup.index = product_lookup.index.astype(int)

The recommend function

In [ ]:
# ── Recommend function ──
def recommend(product_id, top_n=5):
    scores = {
        p2: count
        for (p1, p2), count in co_purchases.items()
        if p1 == product_id
    }
    if not scores:
        print(f"No recommendations found for product {product_id}")
        return pd.DataFrame()

    top = sorted(scores.items(), key=lambda x: x[1], reverse=True)[:top_n]

    result = []
    for pid, score in top:
        if pid in product_lookup.index:
            row = product_lookup.loc[pid]
            result.append({
                "product_id": pid,
                "name": row["name_y"],
                "category": row["category"],
                "times_carted_together": score
            })

    return pd.DataFrame(result)

In [ ]:
# ── Test it ──
sample_product = purchases["product_id"].value_counts().index[0]
sample_name = product_lookup.loc[sample_product, "name_y"]

print(f"\nTop recommendations for: '{sample_name}'")
print(recommend(sample_product))

Top recommendations for: 'Conditioner CornflowerBlue 855'
   product_id                               name category  \
0         709                 Sneakers Beige 851  Fashion
1         510           Moisturizer DarkBlue 988   Beauty
2         385  Lipstick LightGoldenRodYellow 369   Beauty
3         974              E-book LightCoral 987    Books
4         496             Lipstick LightBlue 766   Beauty

   times_carted_together
0                     10
1                      9
2                      9
3                      9
4                      8

In [ ]:
# ── Search by product name (for demo) ──
def recommend_by_name(product_name_query, top_n=5):
    # Find matching products (case-insensitive partial match)
    matches = product_lookup[
        product_lookup["name_y"].str.contains(product_name_query, case=False, na=False)
    ]

    if matches.empty:
        print(f"No product found matching '{product_name_query}'")
        return pd.DataFrame()

    # Take the first match
    product_id = matches.index[0]
    product_name = matches.loc[product_id, "name_y"]
    print(f"Showing recommendations for: '{product_name}'\n")

    return recommend(product_id, top_n)


# ── Test with name search ──
print(recommend_by_name("Headphones"))

Showing recommendations for: 'Headphones LightGray 247'

   product_id                             name     category  \
0         670       Water Bottle BurlyWood 738       Sports
1         377         Moisturizer DarkBlue 603       Beauty
2        1162                 Puzzle Coral 686         Toys
3         772  Jacket LightGoldenRodYellow 571      Fashion
4          24                   SSD Orchid 272  Electronics

   times_carted_together
0                      7
1                      6
2                      6
3                      5
4                      5

In [ ]:
# ── Bonus: show all available products (useful for demo) ──
def show_all_products():
    return (
        product_lookup
        .reset_index()[["product_id", "name_y", "category"]]
        .sort_values("category")
        .reset_index(drop=True)
    )

print(show_all_products())

      product_id                            name_y category
0            454       Sunscreen DarkSlateGray 960   Beauty
1            479          Moisturizer Moccasin 905   Beauty
2            474             Sunscreen DimGray 741   Beauty
3            456       Shampoo MediumTurquoise 528   Beauty
4            404    Conditioner CornflowerBlue 855   Beauty
...          ...                               ...      ...
1192        1144  Building Blocks DarkSeaGreen 909     Toys
1193        1080              Puzzle LimeGreen 221     Toys
1194        1034     Building Blocks LightPink 351     Toys
1195        1082              Board Game Brown 135     Toys
1196        1071             Doll LightSkyBlue 279     Toys

[1197 rows x 3 columns]

In [ ]:
# See all categories in your data
print(product_lookup["category"].value_counts())

In [ ]:
# Test a product from a different category
# Replace "Shirt" with whatever category name you see above
#print(recommend_by_name("Shirt"))
#print(recommend_by_name("Laptop"))
print(recommend_by_name("Book"))

In [ ]:
# Test one product from each category
categories = ["Books", "Home & Kitchen", "Fashion", "Sports", "Beauty", "Toys"]

for cat in categories:
    # Get the most popular product in this category
    sample = (
        purchases[purchases["category"] == cat]["product_id"]
        .value_counts()
        .index
    )
    if len(sample) == 0:
        print(f"\n{cat}: No cart data found")
        continue

    pid = sample[0]
    pname = product_lookup.loc[pid, "name_y"]
    print(f"\n--- {cat} ---")
    print(f"Input product: {pname}")
    print(recommend(pid))

In [ ]:
# MODULE 3: PRODUCT RECOMMENDER — FINAL DEMO

def demo_recommender():
    print("=" * 55)
    print("   SMART E-COMMERCE — PRODUCT RECOMMENDER (Module 3)")
    print("=" * 55)

    # ── Dataset summary ──
    print("\n📦 DATASET SUMMARY")
    print(f"   Total cart events    : {len(purchases):,}")
    print(f"   Unique products      : {purchases['product_id'].nunique()}")
    print(f"   Unique customers     : {purchases['customer_id'].nunique()}")
    print(f"   Product pairs tracked: {len(co_purchases):,}")
    print(f"   Categories covered   : {purchases['category'].nunique()}")

    # ── Category breakdown ──
    print("\n🗂️  PRODUCTS PER CATEGORY")
    for cat, count in product_lookup["category"].value_counts().items():
        print(f"   {cat:<20} {count} products")

    # ── Live recommendations per category ──
    print("\n🎯 SAMPLE RECOMMENDATIONS BY CATEGORY")
    print("-" * 55)

    categories = product_lookup["category"].unique()

    for cat in categories:
        # Get most popular product in this category
        cat_products = purchases[purchases["category"] == cat]["product_id"]
        if cat_products.empty:
            continue

        pid = cat_products.value_counts().index[0]
        pname = product_lookup.loc[pid, "name_y"]
        recs = recommend(pid, top_n=3)

        print(f"\n  📌 Category : {cat}")
        print(f"  Input       : {pname}")
        print(f"  Recommended :")

        if recs.empty:
            print("     No recommendations found")
        else:
            for i, row in recs.iterrows():
                print(f"     {i+1}. {row['name']:<40} ({row['category']}) — score: {row['times_carted_together']}")

    print("\n" + "=" * 55)
    print("  ✅ Module 3 complete — Recommender is working!")
    print("=" * 55)

# ── Run the demo ──
demo_recommender()

=======================================================
   SMART E-COMMERCE — PRODUCT RECOMMENDER (Module 3)
=======================================================

📦 DATASET SUMMARY
   Total cart events    : 143,126
   Unique products      : 1197
   Unique customers     : 19660
   Product pairs tracked: 667,524
   Categories covered   : 7

🗂️  PRODUCTS PER CATEGORY
   Books                171 products
   Home & Kitchen       171 products
   Fashion              171 products
   Sports               171 products
   Beauty               171 products
   Electronics          171 products
   Toys                 171 products

🎯 SAMPLE RECOMMENDATIONS BY CATEGORY
-------------------------------------------------------

  📌 Category : Books
  Input       : Paperback Plum 768
  Recommended :
     1. Paperback Orchid 530                     (Books) — score: 10
     2. E-book PaleTurquoise 502                 (Books) — score: 10
     3. Hardcover Crimson 400                    (Books) — score: 10

  📌 Category : Home & Kitchen
  Input       : Air Fryer MediumTurquoise 924
  Recommended :
     1. Moisturizer Salmon 586                   (Beauty) — score: 10
     2. Doll Gray 206                            (Toys) — score: 10
     3. Puzzle Orchid 600                        (Toys) — score: 9

  📌 Category : Fashion
  Input       : Jacket Violet 280
  Recommended :
     1. Doll CadetBlue 251                       (Toys) — score: 11
     2. Coffee Maker PaleGoldenRod 826           (Home & Kitchen) — score: 8
     3. Dress RoyalBlue 415                      (Fashion) — score: 8

  📌 Category : Sports
  Input       : Dumbbell SlateBlue 979
  Recommended :
     1. Cycling Helmet DarkSalmon 505            (Sports) — score: 10
     2. Hoodie Ivory 379                         (Fashion) — score: 9
     3. Serum SteelBlue 170                      (Beauty) — score: 9

  📌 Category : Beauty
  Input       : Conditioner CornflowerBlue 855
  Recommended :
     1. Sneakers Beige 851                       (Fashion) — score: 10
     2. Moisturizer DarkBlue 988                 (Beauty) — score: 9
     3. Lipstick LightGoldenRodYellow 369        (Beauty) — score: 9

  📌 Category : Electronics
  Input       : Mouse SlateBlue 586
  Recommended :
     1. T-shirt Violet 307                       (Fashion) — score: 9
     2. Board Game Orchid 902                    (Toys) — score: 7
     3. Moisturizer DarkBlue 547                 (Beauty) — score: 6

  📌 Category : Toys
  Input       : Puzzle Orchid 600
  Recommended :
     1. Action Figure BlueViolet 644             (Toys) — score: 11
     2. Board Game DimGray 463                   (Toys) — score: 10
     3. Air Fryer MediumTurquoise 924            (Home & Kitchen) — score: 9

=======================================================
  ✅ Module 3 complete — Recommender is working!
=======================================================

In [ ]:
# ════════════════════════════════════
# SAVE FILES FOR DASHBOARD TEAMMATE
# ════════════════════════════════════
import json

# Save product lookup
product_lookup.reset_index().to_csv("product_lookup.csv", index=False)

# Save co-purchase data
co_purchases_serializable = {str(k): v for k, v in co_purchases.items()}
with open("co_purchases.json", "w") as f:
    json.dump(co_purchases_serializable, f)

print("✅ Files saved!")
print("   → product_lookup.csv")
print("   → co_purchases.json")
print("\n📬 Send both files to your dashboard teammate.")

# Working Product Recommender in Collab

In [ ]:
# ── Install widget support ──
!pip install ipywidgets -q

import ipywidgets as widgets
from IPython.display import display, clear_output

# ── UI Components ──
title = widgets.HTML("<h2>🛒 Smart E-Commerce — Product Recommender</h2>")

category_dropdown = widgets.Dropdown(
    options=["-- Select a category --"] + sorted(product_lookup["category"].unique().tolist()),
    description="Category:",
    style={"description_width": "80px"},
    layout=widgets.Layout(width="400px")
)

product_dropdown = widgets.Dropdown(
    options=["-- Select a product --"],
    description="Product:",
    style={"description_width": "80px"},
    layout=widgets.Layout(width="400px")
)

recommend_button = widgets.Button(
    description="Get Recommendations",
    button_style="primary",
    layout=widgets.Layout(width="200px", margin="10px 0")
)

output = widgets.Output()

# ── When category changes, update product list ──
def on_category_change(change):
    if change["new"] == "-- Select a category --":
        product_dropdown.options = ["-- Select a product --"]
        return

    category = change["new"]
    filtered = product_lookup[product_lookup["category"] == category]
    product_options = ["-- Select a product --"] + [
        f"{row['name_y']} (ID: {idx})"
        for idx, row in filtered.iterrows()
    ]
    product_dropdown.options = product_options
    with output:
        clear_output()

category_dropdown.observe(on_category_change, names="value")

# ── When button is clicked, show recommendations ──
def on_recommend_click(b):
    with output:
        clear_output()

        if product_dropdown.value == "-- Select a product --":
            print("⚠️  Please select a product first.")
            return

        # Extract product ID from dropdown value
        product_id = int(product_dropdown.value.split("ID: ")[1].replace(")", ""))
        product_name = product_dropdown.value.split(" (ID:")[0]

        recs = recommend(product_id, top_n=5)

        # ── FIXED: check if DataFrame is empty ──
        if isinstance(recs, pd.DataFrame):
            if recs.empty:
                print(f"⚠️  No recommendations found for '{product_name}'")
                return
            recs = recs.to_dict(orient="records")
        elif not recs:
            print(f"⚠️  No recommendations found for '{product_name}'")
            return

        # ── Display results ──
        print(f"\n  Input product : {product_name}")
        print(f"  Category      : {category_dropdown.value}")
        print("─" * 55)
        print(f"  ✨ Customers who carted this also carted:\n")

        for i, rec in enumerate(recs):
            print(f"  {i+1}. {rec['name']}")
            print(f"     Category : {rec['category']}")
            print(f"     Score    : {rec['times_carted_together']} customers carted together")
            print()

recommend_button.on_click(on_recommend_click)

# ── Re-display everything ──
display(title, category_dropdown, product_dropdown, recommend_button, output)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 21.1 MB/s eta 0:00:00

HTML(value='<h2>🛒 Smart E-Commerce — Product Recommender</h2>')

Dropdown(description='Category:', layout=Layout(width='400px'), options=('-- Select a category --', 'Beauty', …

Dropdown(description='Product:', layout=Layout(width='400px'), options=('-- Select a product --',), style=Desc…

Button(button_style='primary', description='Get Recommendations', layout=Layout(margin='10px 0', width='200px'…

Output()

In [ ]:
print(get_products("Books")[:5])
print(get_products("Electronics")[:5])
print(get_products("Beauty")[:5])

[{'product_id': 1005, 'name': 'E-book Blue 118', 'category': 'Books'}, {'product_id': 946, 'name': 'E-book RosyBrown 381', 'category': 'Books'}, {'product_id': 931, 'name': 'Hardcover Coral 875', 'category': 'Books'}, {'product_id': 879, 'name': 'Paperback Sienna 127', 'category': 'Books'}, {'product_id': 997, 'name': 'E-book Thistle 364', 'category': 'Books'}]
[{'product_id': 24, 'name': 'SSD Orchid 272', 'category': 'Electronics'}, {'product_id': 84, 'name': 'SSD RosyBrown 174', 'category': 'Electronics'}, {'product_id': 20, 'name': 'Speaker Chocolate 376', 'category': 'Electronics'}, {'product_id': 123, 'name': 'Headphones LightGray 247', 'category': 'Electronics'}, {'product_id': 53, 'name': 'Monitor LemonChiffon 452', 'category': 'Electronics'}]
[{'product_id': 499, 'name': 'Conditioner DarkGoldenRod 688', 'category': 'Beauty'}, {'product_id': 415, 'name': 'Shampoo LawnGreen 601', 'category': 'Beauty'}, {'product_id': 357, 'name': 'Conditioner PeachPuff 275', 'category': 'Beauty'}, {'product_id': 494, 'name': 'Moisturizer SteelBlue 610', 'category': 'Beauty'}, {'product_id': 405, 'name': 'Conditioner LightGray 973', 'category': 'Beauty'}]

In [ ]:
import json

def get_categories():
    return sorted(product_lookup["category"].unique().tolist())

def get_products(category):
    df = product_lookup.reset_index()
    filtered = df[df["category"].str.lower() == category.lower()]
    return filtered[["product_id", "name_y", "category"]].rename(
        columns={"name_y": "name"}
    ).to_dict(orient="records")

categories = get_categories()

products_by_category = {}
for category in categories:
    products_by_category[category] = get_products(category)

with open("products_by_category.json", "w") as f:
    json.dump(products_by_category, f, indent=2)

print("Saved products_by_category.json")

Saved products_by_category.json

In [ ]:
import json
import pandas as pd

def get_recommendations(product_id, top_n=5):
    return recommend(int(product_id), top_n)

demo_product_ids = [973, 670, 377, 24, 772]

demo_recommendations = {}

for pid in demo_product_ids:
    recs = get_recommendations(pid, top_n=5)

    if isinstance(recs, pd.DataFrame) and not recs.empty:
        demo_recommendations[str(pid)] = recs.to_dict(orient="records")

with open("demo_recommendations.json", "w") as f:
    json.dump(demo_recommendations, f, indent=2)

print("Saved demo_recommendations.json")

Saved demo_recommendations.json

In [ ]:
print(get_recommendations(973, top_n=5))

   product_id                         name category  times_carted_together
0         911           Paperback Plum 768    Books                     10
1         974        E-book LightCoral 987    Books                      7
2         623  Water Bottle PapayaWhip 550   Sports                      7
3         958     Hardcover LightGreen 573    Books                      7
4         926              E-book Gray 372    Books                      7

For Danial insert in REACT

In [ ]:
"""
# ── Your friend just calls these directly — no API needed ──

# Get all categories
def get_categories():
    return sorted(product_lookup["category"].unique().tolist())

# Get all products in a category
def get_products(category):
    df = product_lookup.reset_index()
    filtered = df[df["category"].str.lower() == category.lower()]
    return filtered[["product_id", "name_y", "category"]].rename(
        columns={"name_y": "name"}
    ).to_dict(orient="records")

# Get recommendations for a product
def get_recommendations(product_id, top_n=5):
    return recommend(int(product_id), top_n)

# THEN YOUR FRIEND CAN JUST CALL THEM LIKE THIS ANYWHERE IN THE NOTEBOOK
# Example usage
print(get_categories())
print(get_products("Books"))
print(get_recommendations(973))
"""

'\n# ── Your friend just calls these directly — no API needed ──\n\n# Get all categories\ndef get_categories():\n    return sorted(product_lookup["category"].unique().tolist())\n\n# Get all products in a category\ndef get_products(category):\n    df = product_lookup.reset_index()\n    filtered = df[df["category"].str.lower() == category.lower()]\n    return filtered[["product_id", "name_y", "category"]].rename(\n        columns={"name_y": "name"}\n    ).to_dict(orient="records")\n\n# Get recommendations for a product\ndef get_recommendations(product_id, top_n=5):\n    return recommend(int(product_id), top_n)\n\n# THEN YOUR FRIEND CAN JUST CALL THEM LIKE THIS ANYWHERE IN THE NOTEBOOK\n# Example usage\nprint(get_categories())\nprint(get_products("Books"))\nprint(get_recommendations(973))\n'

## **Export Datasets**

In [ ]:
#user_Behaviour_df.to_excel(
#       r"user_behaviours.xlsx",
#    index=False )

In [ ]:
#purchase_user_df.to_excel(
#       r"purchase_user.xlsx",
#    index=False)

In [ ]:
#customer_df.to_excel(
#       r"customers.xlsx",
#    index=False)